### ISSUE TITLE
Jump to commit when updating

### ISSUE THREAD

**Issue by petobens** [Shougo/neobundle.vim#166]
When Neobundle updates a plugin it shows the relevant commits when called with:

    nnoremap <Leader>bu :Unite -no-split -no-start-insert -log
                \ neobundle/update:all<cr>

I think it would be really cool to have an action that allows to select a commit as a candidate and take you to the relevant commit in github (where one can actually see the code with the changes). It is just and idea. If you don't like it just close. Thanks! Your plugins are awesome :-)

**Comment by petobens** [comment]
Hi @Shougo, any chance of adding  ction to Unite update interface that allows to press enter an open the relevant commit in Github? I think vim-plug allows to do something like this (see [here](https://github.com/junegunn/vim-plug/wiki/extra#gx-to-open-github-urls-on-browser)).

**Comment by Shougo** [comment]
No.

Because:
* I don't use the feature.
* It is hard to Implement.

Pull request is wellcome.
The feature should implement by desired people.

**Comment by petobens** [comment]
Okay. Thank you anyway!

**Comment by Shougo** [comment]
I think it is same feature.

https://github.com/Shougo/neobundle.vim/issues/425

**Comment by petobens** [comment]
Indeed. Thanks for reconsidering.
