### ISSUE TITLE
NeoBundleClean does not catch old dir when `directory` is specified

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#268]
I am in the process of migrating to neobundle.

I have noticed that an initially installed bundle `vim-endwise` is not catched by `NeoBundleClean`, if I later change the directory:

    NeoBundleLazy 'tpope/vim-endwise.git', { 'directory': 'endwise',
          \ 'autoload': { 'insert': 1 }}

Both `endwise` and `vim-endwise` exist.

If I rename `vim-endwise` to `vim-endwise.OLD`, `NeoBundleClean` recognized it to be cleaned.

**Comment by Shougo** [comment]
No respeonse.

**Comment by blueyed** [comment]
Sorry. Might have been fixed in the meantime.
