### ISSUE TITLE
Status / detection of remote/branch changes; detect downgrades

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#275]
It would be useful if `NeoBundleCheckUpdate` would provide more information about what update is detected (e.g. by displaying the current remote / branch and where it wants to update to).

I often create local branches and consider them to be more up-to-date than where I have branched them off.

Maybe there could be an option that would consider a bundle up-to-date, if the current HEAD contains the commit of what the update would result in?
After all it's more a down-grade.

**Comment by wsdjeg** [comment]
i think it is due to some plugin need to compile,then will add many file into the plugin directory

**Comment by Shougo** [comment]
I will implement it.

**Comment by Shougo** [comment]
Implemented.
