### ISSUE TITLE
More collaborators are needed

### ISSUE THREAD

**Issue by Shougo** [Shougo/neobundle.vim#277]
neobundle is important plugin manager, but I may make mistake.

https://github.com/Shougo/neobundle.vim/issues/276

To fix fatal bugs/errors like above, I need neobundle more one or two collaborators.
Can you support me?

Needed skill: VimL

Note: After fix bugs/errors, please create commit link in issues or create pull request and merge it.  I must check/improve your commit.

**Comment by ches** [comment]
Hi @Shougo, I see that you have a `Makefile` for Neobundle that installs and runs vim-themis, looks pretty straightforward. Maybe you could add a brief summary to the README for how to run tests (I know it's just `make test`, but an intro helps people discover it), and also how you prefer people to contribute and what you would like some help with?

Thanks for Neobundle, it's fantastic (and all your other Vim work, for that matter :smile:).

**Comment by Shougo** [comment]
Thanks.  I updated README.
