### ISSUE TITLE
NeoBundleLoadCache: order is different than without cache file

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#299]
I have the following in my vimrc, which now suddenly fails (after some updates and clearing the cache), because `tmru` tells me that `tlib` is required, and `loaded_tlib` is not set when `tmru` is loaded.

```
NeoBundle 'tomtom/tlib_vim.git', { 'directory': 'tlib' }
...
NeoBundle 'tomtom/tmru_vim.git', { 'directory': 'tmru' }
```

When looking at the cache file (~/.vim/neobundles/.neobundle/cache), tmru appears before tlib.

It seems like the cache file should get handled in the same order than the `NeoBundle` lines are (without a cache).

`NeoBundleClearCache` works around this once, until the cache gets used again.

**Comment by blueyed** [comment]
The problem with `'depends'` it that the other plugin might not be enabled / used.

For example, I want to make sure vim-startify gets loaded before fugitive (because of the order of VimEnter), but vim-startify should not be enabled/loaded always.

When the order cannot be maintained, then a new option like `'after'` and/or `'before'` would be needed.

**Comment by Shougo** [comment]
> For example, I want to make sure vim-startify gets loaded before fugitive (because of the order of VimEnter), but vim-startify should not be enabled/loaded always.

You should use "autoload.on_source" feature.

			on_source	(List) or (String)
			Load the bundle when the list bundles are loaded.
			Note: If they are not autoload bundles, "on_source"
			hooks are called when |VimEnter| auto command.
			You can call them manually by |neobundle#call_hook()|.

			For example: 
			if neobundle#tap('plugin-B.vim')
			  call neobundle#config({
			        \   'autoload' : {
			        \     'on_source' : [ 'plugin-A.vim' ]
			        \   }
			        \ })
			  call neobundle#untap()
			endif


> When the order cannot be maintained, then a new option like 'after' and/or 'before' would be needed.

I don't want to add the feature.
