### ISSUE TITLE
install or update plugins simutaneously

### ISSUE THREAD

**Issue by kevin4fly** [Shougo/neobundle.vim#323]
please take a look [vim-plug](https://github.com/junegunn/vim-plug)

plugins are able to install or update parallelly, that feature is pretty cool. i hope `neobundle` is able to implement it also. needless to say, `neobundle` is cool and thanks for your effort.

**Comment by petobens** [comment]
I recently tried vim-plug feature and it is incredibly fast. I use neobundle with vimproc and Unite interface but it takes quite some time to update the plugins. Is there any chance to improve the update speed (i.e implement a parallel install method similar to that in vim-plug)?

**Comment by Shougo** [comment]
You can change `g:neobundle#install_max_processes` value...

**Comment by petobens** [comment]
Awesome! I think the default value should be 16. Thank you so much.

**Comment by Shougo** [comment]
Fixed the default value.

**Comment by petobens** [comment]
So I should set the value to 8 instead of 16? Is `max_processes` equivalent to threads?

**Comment by Shougo** [comment]
Yes.  I don't want to change the value.
Because, if I change the default value to 16, it will increase github load.
I think vim-plug default threads value is too big.

**Comment by petobens** [comment]
Ok I see. Thanks
