### ISSUE TITLE
neobundle#begin() breaks unite#filters#matcher_default (more on the description)

### ISSUE THREAD

**Issue by jelera** [Shougo/neobundle.vim#330]
When updating the `neobundle#rc()` to `begin()`, the following errors are being thrown:

```
Error detected while processing /home/jelera/.vimrc:
line  352:
E117: Unknown function: unite#filters#matcher_default#use
line  353:
E117: Unknown function: unite#filters#sorter_default#use
line  355:
E117: Unknown function: unite#custom#source
```

I've sort of found a "solution" by modifying the line 178, changing the `1` for a `0`
`return neobundle#init#_rc(path, 0)`

PS: This are the lines on my vimrc, also added `neobundle#end()` after my plugins lines

```
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
call unite#custom#source('file_mru,file_rec,file_rec/async,grep,locate',
```

**Comment by fhwrdh** [comment]
For the benefit of others, I was seeing the very similar behavior with vundle and the same advice fixed the problem. Thanks much.

**Comment by jabbalaci** [comment]
Same problem and same solution with vim-plug.
