### ISSUE TITLE
Submodule update

### ISSUE THREAD

**Issue by ephexeve** [Shougo/neobundle.vim#354]
Does NeoBundle also update submodules? I am asking this because I am trying to install YCM, I have:

```
NeoBundle 'Valloric/YouCompleteMe', {
     \ 'build' : {
     \     'mac' : './install.sh --clang-completer --system-libclang --omnisharp-competer',
     \     'unix' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
     \     'windows' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
     \     'cygwin' : './install.sh --clang-completer --system-libclang --omnisharp-completer'
     \    }
     \ }
```
So problema 1 is: It doesn't run the build process I have set in the NeoBundle, but that's because the submodules do not exist. if I ```cd``` to YCM and run ./install.sh I get

```
λ wilykat YouCompleteMe → λ git master → ./install.sh --clang-completer
File /Users/ephexeve/.vim/bundle/YouCompleteMe/third_party/ycmd/build.sh doesn't exist; you probably forgot to run:
        git submodule update --init --recursive
```
So I wonder if NeoBundle takes care of the submodules, because in the YCM wiki they tell us to use Vundle, since I do not use Vundle I dunno either if Vundle runs submodules too. 

Thanks.

**Comment by Shougo** [comment]
`:help g:neobundle#types#git#enable_submodule`

Submodule feature is already supported.
I think you should reinstall YCM.

**Comment by jerri** [comment]
submodule-support doesn't seem to work for youcompleteme. After an update I had to manually run the git submodule command and run the installer. Did I miss something?

**Comment by ephexeve** [comment]
@jerri, yes, I had the same problem. @Shougo, any solution here? What seems to be the problem?

**Comment by Shougo** [comment]
I don't know why.  neobundle uses `git pull --recursive`.
Any other solution here?

**Comment by Shougo** [comment]
This problem is update problem instead of install problem?
I will check it.

**Comment by Shougo** [comment]
`git submodule update --init --recursive` is already executed.

```
function! s:type.get_sync_command(bundle) "{{{
  if !executable(g:neobundle#types#git#command_path)
    return 'E: "git" command is not installed.'
  endif

  if !isdirectory(a:bundle.path)
    let cmd = 'clone'
    if g:neobundle#types#git#enable_submodule
      let cmd .= ' --recursive'
    endif

    let depth = get(a:bundle, 'type__depth',
          \ g:neobundle#types#git#clone_depth)
    if depth > 0 && a:bundle.rev == '' && a:bundle.uri !~ '^git@'
      let cmd .= ' --depth=' . depth
    endif

    let cmd .= printf(' %s "%s"', a:bundle.uri, a:bundle.path)
  else
    let cmd = g:neobundle#types#git#pull_command
    if g:neobundle#types#git#enable_submodule
      let shell = fnamemodify(split(&shell)[0], ':t')
      let and = (!neobundle#util#has_vimproc() && shell ==# 'fish') ?
            \ '; and ' : ' && '

      let cmd .= and . g:neobundle#types#git#command_path
            \ . ' submodule update --init --recursive'
    endif
  endif

  return g:neobundle#types#git#command_path . ' ' . cmd
endfunction"}}}
```

Please check the code.

**Comment by Shougo** [comment]
@jerri @ephexeve Please upload minimal .vimrc less than 50 lines.
I will check the behavior.

**Comment by ephexeve** [comment]
Hmm, interesting, @Shougo:

```
let neobundle_readme=expand('~/.vim/bundle/neobundle.vim/README.md')

if !filereadable(neobundle_readme)
  echo "Installing NeoBundle..."
  echo ""
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Valloric/YouCompleteMe', {
     \ 'build' : {
     \     'mac' : './install.sh --clang-completer --system-libclang --omnisharp-competer',
     \     'unix' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
     \     'windows' : './install.sh --clang-completer --system-libclang --omnisharp-completer',
     \     'cygwin' : './install.sh --clang-completer --system-libclang --omnisharp-completer'
     \    }
     \ }

" YCM
set completeopt-=preview
let g:ycm_global_ycm_extra_conf = "~/.ycm_extra_conf.py"
nnoremap <leader>jd :YcmCompleter GoTo<CR>

```

**Comment by Shougo** [comment]
@ephexeve The issue is occurred in using by vimproc?   Please check it.

I tested YouCompleteMe installation by using vimproc, it works.

**Comment by Shougo** [comment]
I tested it in non vimproc environment.  It works.
I think your environment problem.

**Comment by Shougo** [comment]
Please check your git.  "git clone --recursive" is works?
You should try YouCompleteMe clone by command line.

**Comment by Shougo** [comment]
I think it is https://github.com/ekg/freebayes/issues/63 problem.

**Comment by svenstaro** [comment]
I noticed I get this too on a completely fresh system installation. That is, fresh OS, fresh vim. I'm sure my environment is not polluted.

**Comment by Shougo** [comment]
@svenstaro Your "git clone --recursive" works in command line?

**Comment by svenstaro** [comment]
Yes, albeit very slowly. Apparently neobundle just times it out at some point.

**Comment by Shougo** [comment]
OK.  You should change `g:neobundle#install_process_timeout` value.

**Comment by svenstaro** [comment]
Oh! Thanks, I didn't notice this existed. Ok that explains it!

**Comment by Tarrasch** [comment]
Ah,  yea, YouCompleteMe is extremely slow to download. Here's my way around it:

```vim
let g:neobundle#install_process_timeout = 1800  "YouCompleteMe is so slow
NeoBundle 'Valloric/YouCompleteMe', {
            \ 'build' : {
            \   'unix' : './install.sh'
            \ },
\ }
```

I think this solved it for me. But I admit I'm not entirely sure what I'm doing. :)

**Comment by aymericbeaumet** [comment]
@Tarrasch: It worked for me, thanks!

**Comment by Tarrasch** [comment]
Thanks for confirming @aymericbeaumet! :)

**Comment by ephexeve** [comment]
@Tarrasch, forgot to reply. Works like a charm, thanks.
