### ISSUE TITLE
"Not an editor command: NeoBundleInstall"

### ISSUE THREAD

**Issue by soichih** [Shougo/neobundle.vim#355]
I am trying to install NeoBundle on my RHEL6 machine (vim 7.2). When I try to run NeoBundleInstall, I get a message saying "Not an editor command: NeoBundleInstall". I've run the step 1 of the installation procedure. Is there something else that I need to do before I can run it?

**Comment by Shougo** [comment]
Please upload your minimal .vimrc.

**Comment by collegeimprovements** [comment]
I   have the similar problem.
My .vimrc file is blank. Totally blank. Please help.

**Comment by Shougo** [comment]
> My .vimrc file is blank. Totally blank.

It is because your .vimrc is blank.
Please read README documentation.
You must set runtimepath.

```vim
set runtimepath+=~/.vim/bundle/neobundle.vim/
```

I think @soichih has same problem.
