### ISSUE TITLE
How to Uninstall Packages?

### ISSUE THREAD

**Issue by dark-yux** [Shougo/neobundle.vim#356]
How can I remove `:NeoBundle 'vim-scripts/bufkill.vim'` I tried ` :NeoBundleClean 'vim-scripts/bufkill.vim'` with no success.

**Comment by Shougo** [comment]
X:  `NeoBundleClean vim-scripts/bufkill.vim`
O: `NeoBundleClean bufkill.vim`

**Comment by carlitux** [comment]
There is not that command anymore?

**Comment by Shougo** [comment]
Yes...
It is the dangerous command.
You should remove the directory manually.

**Comment by uri** [comment]
Will the plugin still be loaded unless the directory is removed?

**Comment by Shougo** [comment]
> Will the plugin still be loaded unless the directory is removed?

If you remove the plugin configuration from neobundle configurations, it will not be loaded.

**Comment by offero** [comment]
Remove and redownload ALL repos? I liked neobundle precisely because it would manage all my plugins for me. Can you at least provide a way to list out packages that are not managed by neobundle?

**Comment by Shougo** [comment]
You can call `neobundle#commands#clean(bang, ...)` function...

**Comment by MBuchaus** [comment]
Could we maybe setup a config setting to allow danger Will Robinson?

**Comment by HaleTom** [comment]
Couldn't the user be prompted to remove the plugins `[Y]es / [No] / [A]ll?`

**Comment by Shougo** [comment]
Couldn't...
