### ISSUE TITLE
Missing external_commands dependency causes lock file to change

### ISSUE THREAD

**Issue by ches** [Shougo/neobundle.vim#357]
This is not a major problem, I'm just finding a few cases where installing on a new machine when I have a `NeoBundle.lock` present causes some plugins to be installed at different versions than the ones in the lock file. I will update this issue if I can determine reproducible causes of others and work on them, but this one seems clear so wanted to go ahead and open the issue.

I have a plugin configured like this:

```vim
NeoBundleLazy 'swaroopch/vim-markdown-preview', {
\ 'autoload' : { 'filetypes' : 'markdown' },
\ 'external_commands' : 'multimarkdown'
\ }
```

When I `NeoBundleInstall` on a new machine that doesn't have `multimarkdown` installed, `vim-markdown-preview` gets completely removed from the `NeoBundle.lock`. That's somewhat understandable, but it's also annoying: if I want to keep a Vim configuration consistent between multiple systems by using a lock file, I don't want the file to change because of missing system dependencies, I just want the plugins with unsatisfied deps to be disabled quietly.

**Comment by Shougo** [comment]
OK.  I get it.  I will fix it.

**Comment by ches** [comment]
Thanks for the quick change!
