### ISSUE TITLE
Problem with autoloading on insert mode and `doautocmd FileType`

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#359]
I've tried autoloading when entering insert mode (`'autoload': { 'insert': 1
}`) with two plugins (delimitMate and cursorcross).

When editing a python buffer this results in the `&omnifunc` being setup
according to Vim's runtime (`pythoncomplete#Complete`), instead of to what it
should be (`youcompleteme#OmniComplete`).

The problem is that NeoBundle triggers the FileType event after loading the "on
insert" plugins, because they define FileType autocommands:

    delimitMate  FileType
        *         call <SID>DelimitMateDo()
    cursorcross  FileType
        *         silent call cursorcross#on_enter()

The issue is tricky, and the workaround appears to be not using autoloading in
this case, but maybe NeoBundle could be made to only call the new autocommands,
and not trigger the event altogether?!

**Comment by Shougo** [comment]
`'autoload': { 'insert': 1, 'filetypes': 'all' }`
