### ISSUE TITLE
Problems with Installing and working with NeoBundle Windows 7

### ISSUE THREAD

**Issue by kipintouch** [Shougo/neobundle.vim#361]
I am working on a  system with `Windows 7` and [`VIM (7.4)`](https://bitbucket.org/Haroogan/vim-for-windows). I am trying to rewrite my vimrc for multiple-platforms (Win/Unix) alongside `NeoBundle` as plugin manager.

I am getting the following error when I try to use any of the `NeoBundle` Commands **NeoBundleList NeoBundleCheck NeoBundleUpdate** etc. on **Windows 7**

     NeoBundleCheck:
     E117: Unknown function: neobundle#commands#check
     NeoBundleList:
     E117: Unknown function: neobundle#commands#list
     NeoBundleUpdate:
     E117: Unknown function: neobundle#commands#install

I am not sure about what the problem exactly is because commands like `:help neobundle` or function call `call neobundle#get("neobundle.vim")` works with no problems.

Here's a copy of my minimalist vimrc:
   
    " A dictionary containing information about plugins for installation.
    let s:bundle_url = {} 
    let s:bundle_url.autocomplete_ycm  = {
                        \ "url" : "Valloric/YouCompleteMe",
                        \ "opt" : {'vim_version': '7.3.584', 'lazy': 1} }
    let s:bundle_url.format_easy_align   = {
                        \ "url" : "junegunn/vim-easy-align",
                        \ "opt" : {} }
  
    " Get Bundle Url and Options for Installation.
    function! s:Get_Bundle(package)
        if has_key(s:bundle_url, a:package)
            return [s:bundle_url[a:package]["url"], s:bundle_url[a:package]["opt"]]
        else
            echom "No Enteries found for Package " . string(a:package)
            return ["", {}]
        endif
    endfunction

    " This Function Will install all the plugins in the list.
    function! s:Install_All(mylist)
        for k in a:mylist
            let l:my_bundle = s:Get_Bundle(k)
            " !!!!!!!!!!!!! Not sure if this call is the problem !!!!!!!!!!!!!!!!
            call neobundle#bundle(l:my_bundle[0], l:my_bundle[1])
        endfor
    endfunction

    " Note: Skip initialization for vim-tiny or vim-small or With Vim-Starting.
        if !1 | finish | endif
        if has('vim_starting')
            set nocompatible  " Be iMproved
        endif

    " Setup RTP:
        let s:vimfiles = ""
        if has("win32) || has("win64")
             let s:vimfiles = "$VIM/vimfiles/"
        else
              let s:vimfiles = "~/.vim/"
        endif
        let &runtimepath .= ',' . expand(s:vimfiles . "bundle/neobundle.vim/")

    " Let NeoBundle Manage NeoBundle:
        call neobundle#begin(expand(s:vimfiles . "bundle/"))
        NeoBundleFetch 'Shougo/neobundle.vim'

    " Install Other Plugins:
        call s:Install_All(s:blist)
        call neobundle#end()    " End Bundle Installation

        filetype plugin indent on
        syntax on

        if !has('vim_starting')
            " Call on_source hook when reloading .vimrc.
            call neobundle#call_hook('on_source')
        endif

       " Checking bundle
       NeoBundleCheck

**Comment by Shougo** [comment]
* You should remove your functions(`s:Get_Bundle()`, `s:Install_All()`) from the .vimrc.

* neobundle is installed properly?  There is all files?

* Please upload `runtimepath` value after Vim executed.

**Comment by kipintouch** [comment]
`s:Get_Bundle() | s:Install_ALL():`
     I think that they are not the problems. I installed all my plugins individually (`NeoBundle` as manager) and was able to replicate the errors for `NeoBundle + Ultisnips`.

`NeoBundle Files:` Yes, its installed properly. I have deleted the bundle folder multiple times to make that sure.

    RuntimePath:
    C:\Users\doom/vimfiles
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/gruvbox/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-kolor/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/molokai/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/seoul256.vim/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-colors-solarized/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-easy-align/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-multiple-cursors/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-surround/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-origami/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-airline/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/syntastic/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/ack.vim/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-fugitive/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-gitgutter/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vim-snippets/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/ultisnips/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/unite.vim/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/neocomplete.vim/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/vimproc.vim/
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/.neobundle
    C:\Users\doom\Desktop\VIM/vimfiles
    C:\Users\doom\Desktop\VIM
    C:\Users\doom\Desktop\VIM/vimfiles/after
    C:\Users\doom/vimfiles/after
    C:\Users\doom\Desktop\VIM\vimfiles\bundle\neobundle.vim\
    C:/Users/doom/Desktop/VIM/vimfiles/bundle/ultisnips//after

**Comment by Shougo** [comment]
Please create real minimal .vimrc like this:

```vim
" Note: Skip initialization for vim-tiny or vim-small or With Vim-Starting.
    if !1 | finish | endif
    if has('vim_starting')
        set nocompatible  " Be iMproved
    endif

" Setup RTP:
    let s:vimfiles = ""
    if has("win32) || has("win64")
         let s:vimfiles = "$VIM/vimfiles/"
    else
          let s:vimfiles = "~/.vim/"
    endif
    let &runtimepath .= ',' . expand(s:vimfiles . "bundle/neobundle.vim/")

" Let NeoBundle Manage NeoBundle:
    call neobundle#begin(expand(s:vimfiles . "bundle/"))
    call neobundle#end()    " End Bundle Installation

    filetype plugin indent on
    syntax on
```

I will test it.

**Comment by Shougo** [comment]
Please upload your `:scriptnames` output.

> NeoBundle Files: Yes, its installed properly. I have deleted the bundle folder multiple times to make that sure.

Please upload the filelist in neobundle directory.

**Comment by kipintouch** [comment]
ScriptNames:

    "   1: ~\Desktop\TESTING\_vimrc
    "   2: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle.vim
    "   3: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\util.vim
    "   4: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\init.vim
    "   5: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\config.vim
    "   6: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\autoload.vim
    "   7: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\parser.vim
    "   8: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\types\git.vim
    "   9: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\commands.vim
    "  10: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\installer.vim
    "  11: ~\Desktop\TESTING\vimfiles\bundle\NeoBundle.lock
    "  12: ~\Desktop\TESTING\filetype.vim
    "  13: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\ftdetect\vimrecipe.vim
    "  14: ~\Desktop\TESTING\menu.vim
    "  15: ~\Desktop\TESTING\autoload\paste.vim
    "  16: ~\Desktop\TESTING\ftplugin.vim
    "  17: ~\Desktop\TESTING\indent.vim
    "  18: ~\Desktop\TESTING\syntax\syntax.vim
    "  19: ~\Desktop\TESTING\syntax\synload.vim
    "  20: ~\Desktop\TESTING\syntax\syncolor.vim
    "  21: ~\Desktop\TESTING\ftplugin\vim.vim
    "  22: ~\Desktop\TESTING\indent\vim.vim
    "  23: ~\Desktop\TESTING\syntax\vim.vim
    "  24: ~\Desktop\TESTING\syntax\lua.vim
    "  25: ~\Desktop\TESTING\syntax\python.vim

RTP:

    " C:\Users\doom/vimfiles
    " C:/Users/doom/Desktop/TESTING/vimfiles/bundle/.neobundle
    " C:\Users\doom\Desktop\TESTING/vimfiles
    " C:\Users\doom\Desktop\TESTING
    " C:\Users\doom\Desktop\TESTING/vimfiles/after
    " C:\Users\doom/vimfiles/after
    " C:\Users\doom\Desktop\TESTING\vimfiles\bundle\neobundle.vim\

NeoBundle-File List:

    LICENSE-MIT.txt  
    Makefile  
    README.md  
    autoload  
    bin  
    doc  
    ftdetect  
    plugin  
    syntax  
    test

**Comment by Shougo** [comment]
Hm...

`~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\commands.vim` is already loaded.
But `E117: Unknown function: neobundle#commands#check` ?
It is very strange.

This problem is still exists in minimal .vimrc?
Please check.

**Comment by kipintouch** [comment]
Hi, I think I have found temporary solution but I don't know what the **problem** is.

if I place the command `:NeoBundleCheck` after the *neobundle-block* or not use it in my (`.vimrc`)

     neobundle#begin('~/.vim/bundle')
     NeoBundleFetch 'some/plugin'
     ...
     neobundle#end()
     ....
     NeobundleCheck

In this case, the `neobundle\commands.vim` is not loaded. The complete list of `scriptnames`:

     1: ~\Desktop\TESTING\_vimrc
     2: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle.vim
     3: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\util.vim
     4: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\init.vim
     5: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\config.vim
     6: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\autoload.vim
     7: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\parser.vim
     8: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\types\git.vim
     9: ~\Desktop\TESTING\filetype.vim
    10: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\ftdetect\snippets.vim
    11: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\ftdetect\UltiSnips.vim
    12: ~\Desktop\TESTING\menu.vim
    13: ~\Desktop\TESTING\autoload\paste.vim
    14: ~\Desktop\TESTING\ftplugin.vim
    15: ~\Desktop\TESTING\indent.vim
    16: ~\Desktop\TESTING\syntax\syntax.vim
    17: ~\Desktop\TESTING\syntax\synload.vim
    18: ~\Desktop\TESTING\syntax\syncolor.vim
    19: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips.vim
    20: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips\bootstrap.vim
    21: ~\Desktop\TESTING\ftplugin\vim.vim
    22: ~\Desktop\TESTING\indent\vim.vim
    23: ~\Desktop\TESTING\syntax\vim.vim
    24: ~\Desktop\TESTING\syntax\lua.vim
    25: ~\Desktop\TESTING\syntax\python.vim
    26: ~\Desktop\TESTING\colors\peachpuff.vim
    27: ~\Desktop\TESTING\vimfiles\bundle\vim-snippets\plugin\vimsnippets.vim
    28: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\plugin\snipMate_compatibility.vim
    29: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\plugin\UltiSnips.vim
    30: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips\map_keys.vim
    31: ~\Desktop\TESTING\plugin\getscriptPlugin.vim
    32: ~\Desktop\TESTING\plugin\gzip.vim
    33: ~\Desktop\TESTING\plugin\matchparen.vim
    34: ~\Desktop\TESTING\plugin\netrwPlugin.vim
    35: ~\Desktop\TESTING\plugin\rrhelper.vim
    36: ~\Desktop\TESTING\plugin\spellfile.vim
    37: ~\Desktop\TESTING\plugin\tarPlugin.vim
    38: ~\Desktop\TESTING\plugin\tohtml.vim
    39: ~\Desktop\TESTING\plugin\vimballPlugin.vim
    40: ~\Desktop\TESTING\plugin\zipPlugin.vim

On the other hand, *If I place it in the neobundle-block*, something like

     neobundle#begin('~/.vim/bundle')
     NeoBundleFetch 'some/plugin'
     ....
     NeobundleCheck
     neobundle#end()

`neobundle.vim/commands.vim` is loaded correctly. The complete list of `scriptnames`:

     1: ~\Desktop\TESTING\_vimrc
     2: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle.vim
     3: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\util.vim
     4: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\init.vim
     5: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\config.vim
     6: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\autoload.vim
     7: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\parser.vim
     8: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\types\git.vim
     9: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\commands.vim
    10: ~\Desktop\TESTING\vimfiles\bundle\neobundle.vim\autoload\neobundle\installer.vim
    11: ~\Desktop\TESTING\vimfiles\bundle\NeoBundle.lock
    12: ~\Desktop\TESTING\filetype.vim
    13: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\ftdetect\snippets.vim
    14: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\ftdetect\UltiSnips.vim
    15: ~\Desktop\TESTING\menu.vim
    16: ~\Desktop\TESTING\autoload\paste.vim
    17: ~\Desktop\TESTING\ftplugin.vim
    18: ~\Desktop\TESTING\indent.vim
    19: ~\Desktop\TESTING\syntax\syntax.vim
    20: ~\Desktop\TESTING\syntax\synload.vim
    21: ~\Desktop\TESTING\syntax\syncolor.vim
    22: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips.vim
    23: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips\bootstrap.vim
    24: ~\Desktop\TESTING\ftplugin\vim.vim
    25: ~\Desktop\TESTING\indent\vim.vim
    26: ~\Desktop\TESTING\syntax\vim.vim
    27: ~\Desktop\TESTING\syntax\lua.vim
    28: ~\Desktop\TESTING\syntax\python.vim
    29: ~\Desktop\TESTING\colors\peachpuff.vim
    30: ~\Desktop\TESTING\vimfiles\bundle\vim-snippets\plugin\vimsnippets.vim
    31: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\plugin\snipMate_compatibility.vim
    32: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\plugin\UltiSnips.vim
    33: ~\Desktop\TESTING\vimfiles\bundle\ultisnips\autoload\UltiSnips\map_keys.vim
    34: ~\Desktop\TESTING\plugin\getscriptPlugin.vim
    35: ~\Desktop\TESTING\plugin\gzip.vim
    36: ~\Desktop\TESTING\plugin\matchparen.vim
    37: ~\Desktop\TESTING\plugin\netrwPlugin.vim
    38: ~\Desktop\TESTING\plugin\rrhelper.vim
    39: ~\Desktop\TESTING\plugin\spellfile.vim
    40: ~\Desktop\TESTING\plugin\tarPlugin.vim
    41: ~\Desktop\TESTING\plugin\tohtml.vim
    42: ~\Desktop\TESTING\plugin\vimballPlugin.vim
    43: ~\Desktop\TESTING\plugin\zipPlugin.vim

So Far,
- It only happened with UltiSnips Plugin (not sure about others.)
- Only on Windows.

This works for me .. 

Thanks for your help ..

**Comment by Shougo** [comment]
OK.  I get it.  `neobundle#final()` seems remove neobundle plugin path.
But I cannot reproduce it.

Please upload minimal .vimrc and reproduce ways.
Your .vimrc is not minimal executable.

**Comment by bjmiller** [comment]
Take a look at that last entry in the runtimepath:
`C:/Users/doom/Desktop/VIM/vimfiles/bundle/ultisnips//after`

Note the double slash in the path, which breaks things.  This doesn't happen with every plugin, but it does happen with all the ones I've installed that have an /after.  If I remove those items from the runtimepath, everything returns to normal.  Also, if I remove those plugins entirely and reinstall, the runtimepath is correct and everything works.

I hope this helps narrow things down.

**Comment by Shougo** [comment]
Thanks.
