### ISSUE TITLE
Which is a better method for lazy loading a dependent plugin?

### ISSUE THREAD

**Issue by kshenoy** [Shougo/neobundle.vim#362]
I'm trying to make load 'vim-snippets' only if 'Ultisnips' is loaded. Can you please explain which method is preferable while lazy loading a dependent plugin?

1: `NeoBundleLazy 'honza/vim-snippets', { 'disabled': !neobundle#is_sourced('ultisnips') }` or

2: `NeoBundleLazy 'honza/vim-snippets', { 'autoload': { 'on_source': 'ultisnips' } }`

Thanks

**Comment by petobens** [comment]
@Shougo I'm sorry to bother you with a similar doubt but if I want to lazy load a plugin depending on filetype, should I use:

    NeoBundle 'klen/python-mode', {'lazy' : 1,
            \'autoload': { 'filetypes' : ['python'] } }

or directly

    NeoBundle 'klen/python-mode', {'autoload': { 'filetypes' : ['python'] } }

?

**Comment by Shougo** [comment]
`NeoBundleLazy 'honza/vim-snippets', { 'autoload': { 'on_source': 'ultisnips' } }`

is better.

```
NeoBundle 'klen/python-mode', {'autoload': { 'filetypes' : ['python'] } }
```

is not lazy.

**Comment by petobens** [comment]
@Shougo Thank you!
