### ISSUE TITLE
The recipe file 'unite' is not found

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#364]
Minimum vimrc to reproduce this:

set nocompatible
scriptencoding utf-8
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('$HOME/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/neobundle-vim-recipes'
NeoBundle 'Shougo/unite.vim', {'recipe' : 'unite'}
call neobundle#end()
filetype plugin indent on

Both neobundle and neobundle-vim-recipes are installed.

**Comment by paulhybryant** [comment]
However, adding NeoBundleRecipe 'unite' after neobundle#end() works.

**Comment by Shougo** [comment]
Thanks.  It is bug.  I will fix it.

**Comment by Shougo** [comment]
Please use `NeoBundle 'Shougo/neobundle-vim-recipes', {'force': 1}`.

**Comment by paulhybryant** [comment]
Thanks for the quick fix. Can you clarify what 'force' means?
I have the impression that by adding 'force', the bundle will be available before neobundle#end()
Is that the case? Thanks!

**Comment by Shougo** [comment]
"force" is to load the plugin forcelly.
In normal behavior, the runtimepath is lazy loaded until `neobundle#end()`.

**Comment by paulhybryant** [comment]
thanks for the clarification!

On Saturday, February 28, 2015, Shougo <notifications@github.com> wrote:

> "force" is to load the plugin forcelly.
> In normal behavior, the runtimepath is lazy loaded until neobundle#end().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shougo/neobundle.vim/issues/364#issuecomment-76544755>
> .
>


-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.
