### ISSUE TITLE
Improved NeoVim Support

### ISSUE THREAD

**Issue by alem0lars** [Shougo/neobundle.vim#367]
It would be great if `neobundle.vim` supports async *update* / *check* / *install* operations using the NeoVim facilities.

Updating packages in background is **really** awesome, since it doesn't block the UI (i.e. the user) from it's normal operations.

Also, an option to automatically *check* or *check & update* packages every time NeoVim starts would be wonderful.

**Comment by Shougo** [comment]
Unfortunatelly, it is low priority.
The parallel installer is already implemented by vimproc and it works well.
Neovim's new API is not stable and I don't use it in daily task.

**Comment by Shougo** [comment]
> Also, an option to automatically check or check & update packages every time NeoVim starts would be wonderful.

It is impossible.  neovim cannot use jobapi in vim_starting.

**Comment by Shougo** [comment]
Implemented.
