### ISSUE TITLE
Cached ftdetect for lazy plugins only updates on Reinstall

### ISSUE THREAD

**Issue by rafi** [Shougo/neobundle.vim#368]
Reproduce:
1. Delete cached ftdetect files at `.neobundle/ftdetect`
2. Try `NeoBundleClearCache`, `NeoBundleUpdate`, `NeoBundleCheck`
3. Notice `.neobundle/ftdetect` hasn't been re-created
4. Reinstall only **one** existing plugin `:NeoBundleReinstall vim-ansible-yaml`
5. Now `.neobundle/ftdetect` has been created, with **all** plugins' ftdetect files.

Is this intended?
I would expect `NeoBundleUpdate` to update ftdetect files as well..

**Comment by Shougo** [comment]
It is intended behavior.
ftdetect files are updated if the plugins are updated.

> I would expect NeoBundleUpdate to update ftdetect files as well..

I think your plugins are not updated.  So neobundle ignore updating cached ftdetect files.

**Comment by rafi** [comment]
I was trying to fix filetype being overloaded in vimwiki files, so I changed vim-markdown's ftdetect and expected NeoBundle's cache to pick up the change when clear/update/check..
