### ISSUE TITLE
Neobundle needs manual :helpt for itself.

### ISSUE THREAD

**Issue by introom** [Shougo/neobundle.vim#370]
I just did a fresh installation of system, and switched to use neobundle.

But it seems we should exciptly do a :helpt for neobundle *itself*.

**Comment by Shougo** [comment]
`:NeoBundleDocs` is executed when you updated plugins.
I think you don't update by neobundle.

**Comment by introom** [comment]
Sorry? Maybe I am not clear enough.

I was saying the doc for neobundle itself is not generated automatically, not the docs for the plugins managed by neobundle.

Regards.

**Comment by Shougo** [comment]
Please upload minimal .vimrc and reproduce ways from Vim starting.
I will check it.

**Comment by Shougo** [comment]
No response.
