### ISSUE TITLE
autoload won't work with 'insert'

### ISSUE THREAD

**Issue by introom** [Shougo/neobundle.vim#371]
Hi.

This is my minimal conf:
NeoBundleLazy 'Valloric/YouCompleteMe', {
\ 'build': {'unix': './install.sh --clang-completer'},
\ 'autoload': {'insert': 1}}

With the above, after I've entered into the insert mode, I can notice the dir of YCM has been added into the rtp. However, when I type :YcmCompleter, vim errs: it's not an editor command. Seems like the vim files for YCM are not sourced.

With another minima conf:
NeoBundleLazy 'Valloric/YouCompleteMe', {
\ 'build': {'unix': './install.sh --clang-completer'},
\ 'autoload': {'filetypes': ['python', 'c', 'cpp']}}

Everything works.

**Comment by Shougo** [comment]
You must call youcompleteme#Enable() after loaded.

You can use "augroup" feature.

```
						*neobundle-options-augroup*
		augroup		(String)
		Specify an augroup name that the plugin uses for |VimEnter| or
		|GUIEnter| autocmd events.
		Neobundle will call their |VimEnter| or |GUIEnter| autocmds
		automatically when |:NeoBundleSource| is executed.
		Note: You'll want to set this option because some plugins
		rely on autocmds defined for |VimEnter| or |GUIEnter|, but by
		using |:NeoBundleSource| after loading .vimrc, those autocmds
		may get skipped. Some examples are, "fugitive", "NERDTree",
		and "session.vim".

		Examples:
	" NERDTree uses augroup NERDTreeHijackNetrw.
	NeoBundle 'scrooloose/nerdtree', { 'augroup' : 'NERDTreeHijackNetrw'}
	" fugitive uses augroup fugitive.
	NeoBundle 'tpope/vim-fugitive', { 'augroup' : 'fugitive'}
```

**Comment by introom** [comment]
thnx
