### ISSUE TITLE
Maybe NeoBundle forgets to do git submodule update --init --recursive??

### ISSUE THREAD

**Issue by SevenHong** [Shougo/neobundle.vim#373]
Hi Shougo,

I was installing YouCompleteMe with NeoBundle, and I found some submodules of YouCompleteMe were not fetched. I manually fetched by `git submodule update --init --recursive` and the rest of installation procedure worked. YCM is first plugin that I have ever used that requires submodules, so I am not exactly sure if this is YCM specific issue or NeoBundle actually forgets to fetch submodules, but I suspect it's the latter one.

**Comment by Shougo** [comment]
I think your update is timeouted.

https://github.com/Shougo/neobundle.vim/issues/354
https://github.com/Shougo/neobundle.vim/issues/343

**Comment by SevenHong** [comment]
I tested again, and it works. For those who might run into same issue: YouCompleteMe takes time to fetch completely and during that process your vim might look like it's frozen but that's ok, you just have to wait. So don't do Ctrl-C to close vim while YCM is fetching...
