### ISSUE TITLE
'disabled' not working with NeoBundleLazy

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#374]
NeoBundle 'vim-scripts/Vim-Support', {
      \ 'autoload' : { 'filetypes' : ['vim'] },
      \ 'disabled' : 1,
      \ }
works but

NeoBundleLazy 'vim-scripts/Vim-Support', {
      \ 'autoload' : { 'filetypes' : ['vim'] },
      \ 'disabled' : 1,
      \ }
does not.

The bundle will still be loaded in the latter case.

**Comment by Shougo** [comment]
I confirmed it.  It is bug.

**Comment by Shougo** [comment]
Fixed.
