### ISSUE TITLE
Install process timeout override for NeoBundle packages

### ISSUE THREAD

**Issue by tony** [Shougo/neobundle.vim#375]
Regarding #343 

@Shougo : Is it possible to have ``install_process_timeout`` as an option for particular NeoBundles?  I would rather set a shorter default process timeout, but higher one for building things like https://github.com/Valloric/YouCompleteMe, https://github.com/jeaye/color_coded, etc.

Something like:

```viml
NeoBundleLazy 'Valloric/YouCompleteMe',  
      \ {
      \ 'autoload': {'filetypes':['c', 'cpp', 'python', 'objcpp']}, 
      \ 'disabled': (!has('python')),
      \ 'insert': 1,
      \ 'augroup': 'youcompletemeStart',
      \ 'build_commands' : ['cmake', 'make'],
      \ 'install_process_timeout': 480,
      \ 'build': {
      \   'unix': './install.sh --clang-completer --system-libclang --system-boost',
      \ },
      \ }
```

**Comment by Shougo** [comment]
OK.

I will add the feature in next version.
