### ISSUE TITLE
Use relative path to neobundle#get_neobundle_dir for cache / install_info

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#377]
I am trying to use a read-only bind-mount of my dotfiles / vim config in containers.

I am bind-mounting `/root/.dotfiles` to `/home/admin-user` in there.

This results in NeoBundle to not pick up it's cache properly, because `neobundle#installer#get_reinstall_bundles` compares the `installed_path`, which is `/root/...` in the cache, but the bundle's path would be `/home/admin-user/...`.

It would be nice if the install info's and cache's path would be considered to be relative to NeoBundle's dir (`neobundle#get_neobundle_dir`).

**Comment by blueyed** [comment]
In particular, the check in `neobundle#get_not_installed_bundles` needs to be fixed for this.

However, I've worked around it now as follows, using a separate cache file in this case.

    " If the NeoBundle cache exists and is not writable, fall back to using
    " a separate cache in /tmp.
    " This works around cache issues (different paths) when using it through a
    " (read-only) bind mount.
    " Ref: https://github.com/Shougo/neobundle.vim/issues/377
    if len(glob(neobundle#commands#get_cache_file(), 1))
          \ && !filewritable(neobundle#commands#get_cache_file())
      let s:vim_cache = '/tmp/.vim-cache-' . $USER
      if !isdirectory(s:vim_cache)
        call mkdir(s:vim_cache, "", 0700)
      endif
      let g:neobundle#cache_file = s:vim_cache . '/neobundle.cache'
    endif

    if neobundle#has_fresh_cache()
      NeoBundleLoadCache
    else
      ...

**Comment by blueyed** [comment]
`install_info` would probably also need to only save the relative path then.

**Comment by Shougo** [comment]
> It would be nice if the install info's and cache's path would be considered to be relative to NeoBundle's dir (neobundle#get_neobundle_dir).

It would be nice.  But I don't want to change the code for it.
Pull request is wellcome.

**Comment by blueyed** [comment]
I'm glad that you agree! :)

Is it correct that `install_info` and cache handling would need to be changed for that?

(For me the workaround is good enough for now, so I am not likely to get into that in the near future)

**Comment by Shougo** [comment]
If you changed code for it, I will check it.
(I think it is merged in next version because compatibilities problem)

> Is it correct that install_info and cache handling would need to be changed for that?

neobundle saves full path in `bundle.path`.
I think you need modify path conversion in save/load cache.
