### ISSUE TITLE
exists('plugin#function') is false, if declared in NeoBundleLazy

### ISSUE THREAD

**Issue by gcollura** [Shougo/neobundle.vim#378]
Hi Shougo,
thanks for your plugins, they're truly awesome. 
I'm having an issue with the `NeoBundleLazy` command. I'm importing the vim-fugitive plugin this way:
```
NeoBundle 'tpope/vim-fugitive', {
            \ 'augroup' : 'fugitive',
            \ 'commands': [
            \   'Git', 'Gdiff', 'Gstatus', 'Gwrite', 'Gcd', 'Glcd',
            \   'Ggrep', 'Glog', 'Gcommit', 'Gblame', 'Gbrowse'
            \ ],
            \ 'functions' : [ 'fugitive#head', 'fugitive#extract_git_dir' ],
            \ 'autoload': {
            \   'filetypes': 'all'
            \ }}
```
As you can see there's the `fugitive#head` function declared, but when other plugins (in particular vim-airline) try to see if that function exists or not, `echo exists('*fugitive#head')` returns `0`.
Is this the expected behavior?

Thanks for you support!

**Comment by Shougo** [comment]
Unfortunatelly, it is feature.
If you use `:NeoBundleLazy`, the plugin is not loaded until `:NeoBundleSource`.
If you want to use `fugitive` and `vim-airline`, you should not use `NeoBundleLazy`.

**Comment by gcollura** [comment]
Ok, thank you anyway. Have a nice day!
