### ISSUE TITLE
neobundle ver.3.1

### ISSUE THREAD

**Issue by Shougo** [Shougo/neobundle.vim#380]
neobundle ver.3.1 features.

* `neobundle#rc()` is removed.  You must use `neobundle#begin()`/`neobundle#end()` instead.

* Cache interfaces are changed.  You should use `neobundle#load_cache()` for it.

* Cache feature and cache version detection are improved.

* You must `:NeoBundle` lines in `neobundle#begin()`/`neobundle#end()` blocks.

**Comment by renajohn** [comment]
Quick question:

In between `neobundle#begin()` and `neobundle#end()`, can I use commands like `nnoremap` and other vim commands?

I'm asking this question because I had to move `colorscheme base16-monokai` out of this section to make it work.

**Comment by Shougo** [comment]
@renajohn 

```
Q: Colorscheme does not load below code. >
	NeoBundle 'mrkn256.vim'
	colorscheme mrkn256
	...
	neobundle#end()

A: 'runtimepath' is set on |neobundle#end()|.  So it is not set when the
colorscheme executed.  You can use |neobundle-options-force| for it or write
|:colorscheme| command after |neobundle#end()|.
```

**Comment by renajohn** [comment]
I knew the manuel would be useful. Thank you for the pointer.
