### ISSUE TITLE
Does NeoBundle provide a mechanism for checking if a bundle is loaded?

### ISSUE THREAD

**Issue by nfarrar** [Shougo/neobundle.vim#382]
I'd like to programatically enable plugin-specific configuration sections in my vimrc, only if the plugin is loaded. I looked through the docs for something like:

```
if NeoBundleLoaded('PluginName')
  " do plugin specific configuration here
endif
```

But I didn't see anything. Was going to write up my own - my thoughts were that the cleanest/fastest way would be just check rtp to see if the name of the plugin is present, essentially, just this:

```
function! s:PluginEnabled(plugin)
  if &rtp =~ a:plugin
    return 1
  else
    return 0
  endif
endfunction

if s:PluginEnabled('neocomplete.vim')
  " neocomplete configuration here
endif
```

Just wanted to double check first if there's something in NeoBundle I might have missed.

**Comment by davidosomething** [comment]
You can use the on_source hook and if tap
see my neobundle rc https://github.com/davidosomething/dotfiles/blob/master/vim/neobundle.vim

tap is if the bundle is installed and available for sourcing (regardless of if it was actually sourced)

source is when it is actually loaded (which is immediately if you aren't doing lazy, after VimEnter and the autoload parameters are met if you are doing lazy)

**Comment by Shougo** [comment]
Yes, you can use `neobundle#tap()`.

**Comment by nfarrar** [comment]
Thanks so much Shougo. :)
