### ISSUE TITLE
How to handle cache when using TOML?

### ISSUE THREAD

**Issue by kballard** [Shougo/neobundle.vim#383]
The NeoBundle caching support compares the ftime of the cache file against the vimrc file. Because I'm using the TOML support and want to skip the cache if the TOML file changed, my vimrc contains

```vim
if neobundle#has_fresh_cache() &&
      \ neobundle#has_fresh_cache(expand('~/.vim/neobundle/neobundle.toml'))
  NeoBundleLoadCache
else
  NeoBundleFetch 'Shougo/neobundle.vim'

  NeoBundle 'Shougo/vimproc.vim', {
        \ 'build': {
        \    'mac': 'make -f make_mac.mak',
        \    'unix': 'make -f make_unix.mak',
        \    'cygwin': 'make -f make_cygwin.mak',
        \    'windows': 'tools\\update-dll-mingw',
        \   }
        \ }

  call neobundle#load_toml('~/.vim/neobundle/neobundle.toml', {'lazy': 1})

  NeoBundleSaveCache
endif
```

`neobundle#has_fresh_cache()` is now deprecated, and `neobundle#load_cache()` doesn't seem like it can do this same thing. What's the best way to handle this? Perhaps `neobundle#load_cache()` could be changed to take a list of files to compare ftime against, instead of just 1 file?

**Comment by Shougo** [comment]
You should use `neobundle#load_cache('~/.vim/neobundle/neobundle.toml')`.

**Comment by kballard** [comment]
But that won't test the ftime of my `vimrc`. Maybe that's ok, since I _shouldn't_ be defining any new bundles in there besides the existing `neobundle.vim` and `vimproc.vim`.

**Comment by Shougo** [comment]
I don't want to add the feature.  But pull request is wellcome.

**Comment by kballard** [comment]
I think I'll just live with having it only check the TOML file.
