### ISSUE TITLE
Multiple neobundle#begin()/neobundle#end() blocks

### ISSUE THREAD

**Issue by sushengloong** [Shougo/neobundle.vim#387]
Hi,

Is it possible to have multiple `neobundle#begin()`/`neobundle#end()` blocks, each in a different `.vim` file?

I tried this but only the last added `.vim` file loaded plugins successfully.

Thanks,
Sheng-Loong

**Comment by Shougo** [comment]
Unfortunatelly, I cannot support the feature.
Because, `neobundle#begin()` resets the RTPs to support multiple .vimrc loading.

@sushengloong Why do you need the feature?   Please explain it.

**Comment by sushengloong** [comment]
Thanks for answering, @Shougo. 

I am using vim config files from https://github.com/neo/vim-config, of which the .vimrc looks like the following:-

```vim
set rtp+=~/.vim/bundle/neobundle.vim/

runtime! custom_preconfig/*.vim
runtime! common_config/*.vim
runtime! custom_config/*.vim

... (truncated)
```

This setup allows user to customize config or add custom plugins in `~/.vim/custom_preconfig/*.vim` or `~/.vim/custom_config/*.vim`, as mentioned at https://github.com/neo/vim-config#user-content-customizing.

There is already a `neobundle#begin()`/`neobundle#end()` block in the common_config folder which includes a bunch of plugins by default. So calling NeoBundle in custom_preconfig or custom_config will cause the warning below on startup:-

```[neobundle] `NeoBundle` commands must be executed within a neobundle#begin/end block.  Please check your usage.```

What are your thoughts on this? Thanks.

**Comment by Shougo** [comment]
OK.  I will add `neobundle#append()` block.
You can use `neobundle#append()` instead of `neobundle#begin()`.
It does not reset rtps.  But you must call `neobundle#begin()` before call `neobundle#append()`.
`neobundle#begin()` initializes neobundle.

**Comment by Shougo** [comment]
Implemented it.

**Comment by sushengloong** [comment]
Awesome, it works like a charm.
Many thanks, @Shougo!
