### ISSUE TITLE
NeoBundleSource doesn't accept single-quoted strings

### ISSUE THREAD

**Issue by kevinushey** [Shougo/neobundle.vim#389]
A somewhat minor problem -- the following does not work for sourcing a script:

```viml
NeoBundleLazy 'scrooloose/syntastic'
autocmd FileType javascript NeoBundleSource 'scrooloose/syntastic'
```

While this does:

```viml
NeoBundleLazy 'scrooloose/syntastic'
autocmd FileType javascript NeoBundleSource "scrooloose/syntastic"
```

Is there any reason for that? I know that Vundle (for some reason) only accepted single quotes for `Bundle` calls; it would be nice if `NeoBundle` would accept both forms consistently (or at least warn about the incompatible form)

**Comment by Shougo** [comment]
You must use like this : `:NeoBundleSource syntastic`.

**Comment by Shougo** [comment]
You should use 'filetypes' feature.

```vim
NeoBudleLazy 'scroolose/syntastic', {
\ 'filetypes' : 'javascript'
\}
```

**Comment by kevinushey** [comment]
Thanks. I see a motivating example is indeed part of `:help :NeoBundleLazy`; sorry for forcing you to repeat yourself.
