### ISSUE TITLE
Docs unclear about "complete" entry for a "command"

### ISSUE THREAD

**Issue by alem0lars** [Shougo/neobundle.vim#393]
I'm using NeoBundleLazy to load the Unite plugin. I've seen in the docs that it should have the autoload command: `{'name': 'Unite', 'complete': 'customlist,unite#complete_source'}`.

The docs say: "The type of completion supported for the input".
But I don't understand what it means in the context of autoloading a plugin..

What does it mean the "complete" entry?

**Comment by Shougo** [comment]
OK.
Lazy command loading feature defines new command.
But the completion is not defined.  Because, it is dummy command.
The "complete" is completion for dummy commands.

**Comment by alem0lars** [comment]
It's still unclear.

Why do I have to specify a 'complete' option there?

I mean, I've thought specifying 'commands' is for lazy loading the plugin when the user types the one command which name matches that list.

What does 'complete' have to do with the loading behaviour?

**Comment by Shougo** [comment]
@alemou0lars You don't have to specify 'complete' option.
It is not needed.
But you may want to complete dummy command arguments.

**Comment by alem0lars** [comment]
Ah ok thanks :)
