### ISSUE TITLE
script_type breaks bundle installation

### ISSUE THREAD

**Issue by ressu** [Shougo/neobundle.vim#396]
I was debugging an issue I encountered with vimproc and turns out it's a NeoBundle issue. (original issue here https://github.com/Shougo/vimproc.vim/issues/200)

I'm using this this snippet as my vimrc for testing:
``` VimL
set nocompatible
set runtimepath+=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('/tmp/bundle'))
NeoBundle 'Shougo/vimproc.vim', {'script_type' : 'plugin',}
call neobundle#end()
NeoBundleCheck
```

If script type is defined, the bundle is installed to `<bundle_root>/plugin_name/<script_type>` in the above case I now have `/tmp/bundle/vimproc.vim/plugin` directory with the vimproc.vim repository. Removing script type will cause the repository to be cloned to the proper location.

**Comment by Shougo** [comment]
It is feature.
It is for bare single file plugin.

```vim
		NeoBundle 'https://raw.github.com/m2ym/rsense/master/etc/rsense.vim',
		\ {'script_type' : 'plugin'}
		NeoBundle 'https://github.com/bronzehedwick/impactjs-colorscheme',
		\ {'script_type' : 'colorscheme'}
```

**Comment by Shougo** [comment]
Please see the documentation:

```
		Note: You must not specify it for categorized plugins.
```

**Comment by ressu** [comment]
If this is a feature, then using the recipe bundle at https://github.com/Shougo/neobundle-vim-recipes will cause vimproc to be installed incorrectly. I initially stumbled on to this when trying to deduce why I can't use NeoBundleRecipe to install vimproc. I can remove the recipes and revert back to manual configurations, but still it's confusing to someone who doesn't know the internals.

**Comment by Shougo** [comment]
Oh, I get it.  It is the recipe's bug.

**Comment by Shougo** [comment]
Removed "script_type" from the recipes.

**Comment by ressu** [comment]
Thanks.
