### ISSUE TITLE
Disabled bundle is installed in NeoBundleUpdate.

### ISSUE THREAD

**Issue by DeaR** [Shougo/neobundle.vim#398]
Note: Disabled plugins are not ignored when install/update
		plugins.

#### .vimrc
```vim
set runtimepath+=~/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundle 'Shougo/unite.vim', {'disabled':1}
call neobundle#end()
```

#### NeoBundleInstall
```vim
:NeoBundleInstall
:NeoBundleLog
[neobundle/install] Target bundles not found.
[neobundle/install] You may have used the wrong bundle name, or all of the bundles are already installed.
```
OK

#### NeoBundleUpdate
```vim
:NeoBundleUpdate
:NeoBundleLog
[neobundle/install] Update started: (2015/07/27 18:30:01)
[neobundle/install] (1/1): |unite.vim| git clone --recursive https://github.com/Shougo/unite.vim.git "C:/Home/DeaR/bundle/unite.vim"
[neobundle/install] (1/1): |unite.vim| Updated
[neobundle/install] |unite.vim|  -> 515b01c64bd92ade146898d5ff7ad7d81a9adc2f
[neobundle/install] Helptags: done. 1 bundles processed
[neobundle/install] Installed/Updated bundles:
[neobundle/install] unite.vim
[neobundle/install] Update done: (2015/07/27 18:30:29)
```
NG

#### Comment(JP)
https://github.com/Shougo/neobundle.vim/blob/master/autoload/neobundle/commands.vim#L47
ここだけであれば上記を修正すればいいのだが
他にも`neobundle#config#get_neobundles()`が使われていて
Disabled bundleは除いた方が良さそうな箇所が他にもあるように見える為(e.g. `NeoBundleClean`, `NeoBundleGitGc`)
`neobundle#config#get_enabled_bundles()`でも作った方が良さそうな感じ
如何せん該当箇所が意外と多い、且つ深くて微妙に判断しづらい箇所もチラホラなので
取り敢えずまだissueのみ

source等は行われない筈なので動作上の実害は無いが、`build`を設定している場合は走ってしまう

**Comment by Shougo** [comment]
それはなかなか面倒くさそう。
残念ながら私にはそれを修正する時間がないので、お願いします。

**Comment by DeaR** [comment]
`NeoBundleInstall`, `NeoBundleUpdate`, `NeoBundleClean`,
`NeoBundleGc`, `NeoBundleDocs`, `Unite neobundle/install`
の動作部分に係る箇所を修正

====

`NeoBundleList`, `Unite neobundle`
はどう扱うか検討

1.  リストアップしない
2. 未インストールと同じ`X`
3. 新しい記号(例:`!`

====

grepするとまだいっぱい`neobundle#config#get_neobundles`を
使用している箇所は出てくるが検証が大変なので保留

**Comment by Shougo** [comment]
テストはちゃんと動いてますか？
テスト増やすべきかもですね

**Comment by Shougo** [comment]
@DeaR これの作業はいまどういった状況ですか。マージできそうでしょうか。

**Comment by DeaR** [comment]
あ、追加のテストを作ろうとしてtodoに積みっぱなしになったままでした
来週中にはけりを付ける方向で作業します

**Comment by Shougo** [comment]
了解しました。では、それまで待つことにします。

**Comment by Shougo** [comment]
@DeaR
https://github.com/Shougo/neobundle.vim/pull/419

現在、上記ブランチで sourced のリファクタリングをやっています。
disabled feature に関しても挙動を変更したので @DeaR さんの手元でもマージと動作の確認をお願いします。
