### ISSUE TITLE
Vim(helptags):E154: Duplicate tag ":NeoBundleInstall"

### ISSUE THREAD

**Issue by kenanpelit** [Shougo/neobundle.vim#400]
Can you help please?

<pre>
 Same revision.
    No new bundles installed.
    Error generating helptags:
    Vim(helptags):E154: Duplicate tag ":NeoBundleInstall" in file /home/kenan/.vim/bundle/.neobundle/doc/neobundle.txt
    Completed. 
</pre>

**Comment by DeaR** [comment]
Please create minimal .vimrc.

**Comment by kenanpelit** [comment]
I found it. This problem was that junegunn/vim-github-dashboard of the same tag (NeoBundleInstall) . Obviously that's his problem. 

https://github.com/junegunn/vim-github-dashboard/blob/master/doc/github_dashboard.txt

You can turn off in this issue.

**Comment by peidong** [comment]
How do you fix this Duplicate tag issue? I want to rewrite the doc file.

**Comment by Shougo** [comment]
@peidong Please remove the duplicated tag from the doc file.
It is the documentation bug.
