### ISSUE TITLE
NeoBundleInstallエラー

### ISSUE THREAD

**Issue by BrokenRadio** [Shougo/neobundle.vim#401]
READMEに書かれている通り、.vimrcに設定を追加して
NeoBundleInstallをすると以下のエラーがでます。
<pre>
function neobundle#commands#install..<SNR>25_install..neobundle#installer#sync..neobundle#util#system の処理中にエラーが検出されました:
行    7:
E484: Can't open file /var/folders/zk/_mq20ml93jb67gt1054d7gy40000gn/T/voEGr9Q/7
function neobundle#commands#install..<SNR>25_install の処理中にエラーが検出されました:
行   18:
</pre>
vimprocを取得してくるところ？エラーになっているようで、
手動でvimprocをインストールしたらエラーは出なくなりました。

こちらの環境は、
OS:Mac OS X Yosemite 10.10.4
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 23 2015 13:33:30)
です。

自己解決済みですが、念のため報告しておきます。

**Comment by Shougo** [comment]
vimproc のアドレスが間違っていたとかではないでしょうか

**Comment by BrokenRadio** [comment]
原因わかりました。
どうやら、.vimrcに
<pre>
set shell=/bin/sh
</pre>
と書いておかないと
<pre>
call system("git clone git://github.com/Shougo/vimproc ~/.vim/bundle/vimproc")
</pre>
でエラーになる模様。どちらかというとVimの方の問題ですね。
失礼しました。
