### ISSUE TITLE
function_prefix for lazy bundles might be wrong / should be a list

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#403]
I have noticed that for delimitMate, the `function_prefix`, which is used for `s:lazy_rtp_bundles` in `autoload/neobundle/config.vim` is not handled/parsed correctly.

The config:

      NeoBundleLazy 'Raimondi/delimitMate', { 'autoload': { 'insert': 1, 'filetypes': 'all' }}

This happens in https://github.com/Shougo/neobundle.vim/blob/5ec955740d45cd5162fa257fde89b151477e294d/autoload/neobundle/parser.vim#L301-309:

    function! neobundle#parser#_function_prefix(name) "{{{
      let function_prefix = tolower(fnamemodify(a:name, ':r'))
      let function_prefix = substitute(function_prefix,
            \'^vim-\|-vim$', '','')
      let function_prefix = substitute(function_prefix,
            \'^unite-', 'unite#sources#','')
      let function_prefix = tr(function_prefix, '-', '_')
      return function_prefix
    endfunction"}}}

I think `function_prefix` should be a list instead, and contain all files' basename in the bundles' rtp's `autoload` dirs, e.g. for a plugin with `autoload/delimitMate.vim` and `autoload/foo.vim`, both `delimitMate` and `foo` should be in `function_prefixes`.

The bundle:

    {'orig_name': 'Raimondi/delimitMate',
     'fetch': 0,
     'resettable': 0,
     'description': '',
     'orig_arg': '''Raimondi/delimitMate'',
     { ''autoload'': {
        ''insert'': 1,
        ''filetypes'': ''all''
        }}',
    'lazy': 1,
    'dummy_commands': [],
    'autoload': {'filetypes': ['all'], 'insert': 1},
    'type': 'git',
    'default': '_',
    'overwrite': 1,
    'uri': 'https://github.com/Raimondi/delimitMate.git',
    'depends': [],
    'external_commands': {},
    'name': 'delimitMate',
    'rtp': '/home/user/.vim/neobundles/delimitMate/',
    'base': '/home/user/.vim/neobundles',
    'normalized_name': 'delimitMate',
    'local': 0,
    'sourced': 0,
    'dummy_mappings': [],
    'focus': 0,
    'gui': 0,
    'stay_same': 0,
    'recipe': '',
    'called_hooks': {},
    'directory': 'delimitMate',
    'orig_opts': {'lazy': 1, 'autoload': {'filetypes': ['all'], 'insert': 1}, 'recipe': '', 'default': '_'},
    'build_commands': {},
    'disabled': 0,
    'terminal': 0,
    'install_process_timeout': 120,
    'install_rev': '',
    'force': 0,
    'rev': '',
    'augroup': 'delimitMate',
    'orig_path': 'Raimondi/delimitMate',
    'vim_version': '',
    'verbose': 0,
    'hooks': {},
    'script_type': '',
    'path': '/home/user/.vim/neobundles/delimitMate'}
    add_lazy: delimitMate delimitMate

I've only noticed this when running vim with `-V15`, which triggered another behavior in Neobundle (see https://github.com/Shougo/neobundle.vim/pull/402 for a fix), and I've found this while investigating.

**Comment by Shougo** [comment]
I don't think so.
It is not useful and it will be long parse time.

**Comment by blueyed** [comment]
Please consider re-opening the issue to track it.

The parsing would be done on demand, and would therefore speed up the processing in general - because often it is not required at all to set the `function_prefix` in advance.

The function would be similar to `s:is_reset_ftplugin` in `autoload/neobundle/config.vim`.

**Comment by Shougo** [comment]
OK.  I will remove the feature.

**Comment by Shougo** [comment]
Implemented.
