### ISSUE TITLE
Installed plugin at Detached HEAD

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#405]
The status of the repositories containing the installed plugins show (Detached) instead of being at the master branch. Is this intended?

Thanks,

**Comment by Shougo** [comment]
https://github.com/Shougo/neobundle.vim/issues/310

It seems same behavior.
But I don't know why.

Please update minimal .vimrc and reproduce ways.

**Comment by paulhybryant** [comment]
Here is the minimal .vimrc and steps to reproduce, using 'tpope/vim-flagship' as the bundle to install

~/.vimrc.repro

set nocompatible
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'tpope/vim-flagship'
call neobundle#end()
NeoBundleCheck
filetype plugin indent on

vi -u ~/.vimrc.repro

The bundle installs fine in this case (branch is 'master').

rm -rf ~/.vim/bundle/vim-flagship
vi -u ~/.vimrc.repro

The bundle will install and in DETACHED state

I think this has something to do with the informations saved in NeoBundle.lock
After deleting the line in NeoBundle.lock related to vim-flagship, the installation is ok again.

**Comment by Shougo** [comment]
Aha.  It is feature.
