### ISSUE TITLE
NeoBundleUpdate fails when the current buffer is .vimrc and bundles contains `ultisnips`

### ISSUE THREAD

**Issue by albertnetymk** [Shougo/neobundle.vim#406]
## How to reproduce the problem

1. Open `.vimrc` file using vim

    ```
    vim ~/.vimrc
    ```
2. Install all bundles.

    ```
    :NeoBundleInstall
    ```
3. Update all bundles

    ```
    :NeoBundleUpdate!
    ```
4. Check update status

    ```
    :NeoBundleLog
    ```
    Get some error message in the log:

    ```
    ...
    [neobundle/install] Error installing bundles:
    [neobundle/install] neobundle.vim ultisnips
    ...
    ```
    
The weird thing is that if I remove the `ultisnips` line, repeat the above process, then the update succeeds.

## .vimrc

```
if has('vim_starting')
  if &compatible
    set nocompatible
  endif

  runtime macros/matchit.vim
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/neobundle-vim-recipes', {'force': 1}
NeoBundleRecipe 'vimproc.vim'
NeoBundle 'SirVer/ultisnips.git'
call neobundle#end()
filetype plugin indent on
```

**Comment by Shougo** [comment]
I cannot reproduce the problem.  It is not neobundle issue.
You should reinstall the plugins.

**Comment by albertnetymk** [comment]
OK, this problem probably has nothing to do with `ultisnips`. I Looked at the source code, and added some print statements to diagnose the problem. My observation is that in function `neobundle#installer#sync`, it creates a subprocess `git pull ... && git submodule ...`. After that, the parent process changes the directory, which somehow affects the current directory of the subprocess. Confirmed by using `pwd && pwd`. The two `pwd` print different result.

**Comment by Shougo** [comment]
Confirmed.  It is vimproc problem.
I will fix it.

**Comment by Shougo** [comment]
Fixed.  Please update vimproc.

**Comment by albertnetymk** [comment]
Confirmed; working now. Thank you very much.
