### ISSUE TITLE
sourced unnecessary bundle by function_prefixes

### ISSUE THREAD

**Issue by DeaR** [Shougo/neobundle.vim#407]
#### 現象1
4cd265887062dc261bdb49e33aab14df44ee147c により
`function_prefix`オプションが廃止され
`function_prefixes`が自動生成されるようになりましたが
これにより不必要なものまでsourceしてしまっている
例: `vimfiler`が`VimEnter`時に`vital#of`によって、全ての`vital`を使用している物がsource

#### 現象2
起動時に適当なautoload関数(`vital#of`とか)を関数内から呼び出していたりすると
`FuncUndefined`が発生して`globpath`が使用される処理コストのかかりそうな処理が走る
しかもそれは`NeoBundleSaveCache`より後だとcacheにも残らない
(但しcacheに残すとなるとUpdateによってautoload直下が増減した際に追従できない)

#### 修正案1
`function_prefixes`をオプション化、
デフォルト値は`neobundle#parser#_function_prefix(bundle.name)`、
それ以外も反応させたければ各自で定義、
辺りが無難な落とし所かな、と
(単に`function_prefix`がListを許容するようになっただけ)

#### 修正案2
`vital#`を除外
但し根本解決にはなってない(現象2は未解決)

#### 私見
特に`vital`の爆発力は凄い
私の環境では大丈夫だったが
`textobj-user`や`operator-user`も飛び火したりすると凄い事になりそう

別件だがオートロード関数を呼んだ際に`FuncUndefind`が
呼び出し元がトップレベルだと発生しないのに
関数内だと発生した上で正常に呼び出されるのが何とも気持ち悪く感じる

**Comment by Shougo** [comment]
報告ありがとうございます。対応しました。

**Comment by Shougo** [comment]
一応ここで説明しておきますが、今回は現象2 には対応していません。

textobj-user, operator-user では爆発しないようになっているので大丈夫です。

現象2 に対応していない理由は、globpath 自体はそこまで大きいコストではない(私の
環境で 5ms 程度)のと無意味にオプション追加するのは好まないからです。

そもそも、.vimrc で lazy している autoload 関数を呼びだしている時点で lazy には
なっていないし、読み込みコストは許容されるべきです。

**Comment by DeaR** [comment]
> textobj-user, operator-user では爆発しないようになっているので大丈夫です。

あ、はいソース見てファイル名からのみの参照に変わってたので
textobj-user等が大丈夫だろうと思われるのは確認してました

> 現象2 に対応していない理由は、globpath 自体はそこまで大きいコストではない(私の
> 環境で 5ms 程度)

うちの環境だと0.05秒(50ms)くらいですかね
reltime調べかつwindowsなのでちゃんとは調べていませんが

> 無意味にオプション追加するのは好まないからです。

function_prefixは元々存在してたんで追加という感覚では無かった

> そもそも、.vimrc で lazy している autoload 関数を呼びだしている時点で lazy には
> なっていないし、読み込みコストは許容されるべきです。

別にlazyじゃないautoload関数でもそれが関数内であればFuncUndefinedが発生してしまいます
vim-jp/issues#755
なのでneobundle#tapped.hooks.on_source内でsingleton#enableとかunite#○○のようにオートロード関数で初期設定等を行うだけでglobpathの処理が発生してしまいます

**Comment by DeaR** [comment]
あぁ、ファイル名からのみになったから
autofmtやtextobj-userのようなautoload直下がフォルダだけなのは
functionsで設定しないと読み込まないのか

**Comment by Shougo** [comment]
> あぁ、ファイル名からのみになったから
> autofmtのようなautoload直下がフォルダだけなのは
> functionsで設定しないと読み込まないのか
> まぁ数は多くないんで大したことないか

これは直します

**Comment by Shougo** [comment]
修正しました

**Comment by DeaR** [comment]
:+1:
