### ISSUE TITLE
autoload issue with vimfiler

### ISSUE THREAD

**Issue by petobens** [Shougo/neobundle.vim#408]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')


if has('vim_starting')
    execute 'set runtimepath+=' . expand('$DOTVIM/bundle/neobundle')
endif
call neobundle#begin(expand('$DOTVIM/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim', {'name' : 'neobundle'}
NeoBundle 'Shougo/vimfiler', {'lazy' : 1, 'autoload' : {
        \ 'commands' : ['VimFilerBufferDir', 'VimFiler',
        \ 'VimFilerCreate', 'VimFilerTab'],
        \ 'explorer' : 1
        \ }
        \ }
call neobundle#end()

filetype plugin indent on

call vimfiler#custom#profile('default', 'context', {
            \ 'direction' : 'topleft'})
call vimfiler#set_execute_file('pdf,PDF', 'SumatraPDF')
```

Now open Gvim. You will get the following error:

![screenshot-22-08-2015_10-47-43](https://cloud.githubusercontent.com/assets/2583971/9424231/44f5775e-48bb-11e5-8f49-d7cfa1536355.png)

I think the problem might be related to the recent changes in autoload function.

**Comment by Shougo** [comment]
Yes, it is feature.
You should not vimfiler as lazy if call it in initialization.

**Comment by petobens** [comment]
@Shougo, I don't quite understand your answer. Why I cannot lazy load vimfiler? For example doing:

```vim
NeoBundle 'thinca/vim-unite-history', {'lazy' : 1,
        \ 'unite_sources' : ['history/command', 'history/search']
        \ }
```
works just fine.

**Comment by Shougo** [comment]
@petobens Your vimfiler defines as lazy.
But it is not lazy.  Because, it calls vimfiler functions in .vimrc.

**Comment by petobens** [comment]
Ahh okok. Thanks @Shougo.
