### ISSUE TITLE
How to setup a config based approach for loading a list of plugins at start up.

### ISSUE THREAD

**Issue by symbolix** [Shougo/neobundle.vim#412]
Hi,

I would like to have a centralized way of enabling and disabling plugins at VIM start up. I kind of do it inside a start up script where I have IF blocks and variables etc. But I am wondering if there is a way to do it out of the box.

Here is how I do selective plugin loading right now:

    let s:active = 1
    if s:active
        " Let NeoBundle manage the bundle
        call myPlugin#verboseMessage("Plugin is ACTIVE. ")
        NeoBundle 'Shougo/unite.vim'
    else
        call myPlugin#verboseMessage("Plugin is DISABLED. ")
    endif

Obviously, all this happening between the

    call neobundle#begin('~/.vim/bundle/')

and the

    call neobundle#end()

blocks

The question is: is there a way to do this with one single configuration file? For example, something that looks like:

    {
        'unite': 0,
        'vimproc': 1,
        'neocomplcache': 1,
        'syntastic': 0,
    }

So the pseudo code above, will skip the loading of *unite* and *syntastic* at start up, but will still load *vimproc* and *neocomplcache*.

Just would like to check if there is already a way to do that, so that every time I want to switch plugins off, I do not have to edit my start up vim scripts but only update that config file.

Thanks.

**Comment by Shougo** [comment]
No.  I don't want to add the feature.
But you can use "disabled" for it.
