### ISSUE TITLE
NeoBundleDisable not working

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#414]
Example:

...
NeoBundle 'Raimondi/delimitMate'
NeoBundleDisable 'delimitMate'
...
call neobundle#end()

The disabled bundle will still be sourced.

**Comment by Shougo** [comment]
`NeoBundleDisable delimitMate` is correct.

**Comment by paulhybryant** [comment]
Thanks.

**Comment by paulhybryant** [comment]
Hi Shougo,

There is one issue with this though.
When I have a list of plugin that I want to disable (don't want to add a 'disabled' key in the options and change the value to 0 or 1 each time I want to disable some of them), the following won't work:

for bundle in ['delimitMate']
  NeoBundleDisable bundle
endfor

**Comment by symbolix** [comment]
Hi paulhybryant,

Is it ok if we join forces on this one? Please see my issue #412 

I am trying to implement a similar *config* based approach where I would like to iterate through a dictionary of plugins and enable/disable them. I am curious to see how the *NeoBundleDisable* *bundle* approach will work. Does it have to be inside a

    call neobundle#begin()
    ...
    call neobundle#end()

block? etc.

Thanks.

**Comment by Shougo** [comment]
> There is one issue with this though.
> When I have a list of plugin that I want to disable (don't want to add a 'disabled' key in the options and change the value to 0 or 1 each time I want to disable some of them), the following won't work:

You should use the code like this:

```vim
for bundle in ['delimitMate']
    execute 'NeoBundleDisable' bundle
endfor
```

**Comment by Shougo** [comment]
> I am trying to implement a similar config based approach where I would like to iterate through a dictionary of plugins and enable/disable them. I am curious to see how the NeoBundleDisable bundle approach will work. Does it have to be inside a

No.  But it should be.

**Comment by paulhybryant** [comment]
It works using execute. Thanks!

**Comment by symbolix** [comment]
Hi Shogu,

Thanks for the explanation and the example.

> No. But it should be.

So, is it possible to perform the *disable* operation inside a function or does it have to always be at startup?

    function! myPlugin#disablePlugins()
    call neobundle#begin(expand('~/.vim/bundle'))

    for bundle in ['banana', 'apple', 'house', 'foo']
        execute 'NeoBundleDisable' bundle
    endfor
    
    call neobundle#end()
    endfunction

**Comment by Shougo** [comment]
> So, is it possible to perform the disable operation inside a function or does it have to always be at startup?

Yes, but `neobundle#begin()` clears plugins configuration.

**Comment by symbolix** [comment]
Ok. Thanks. I will keep everything at start up, between the *begin* and *end* blocks. I guess there is not much use of a process that will *disable* and *enable* plugins without re-starting Vim? Apart from the already implemented

    neobundle#config({
        \   'autoload' : {
        \     <some condition>
        \   }
        \ })

technique.

Thanks.

**Comment by Shougo** [comment]
> I guess there is not much use of a process that will disable and enable plugins without re-starting Vim?

You can disable Plugins after Vim startup.
But Vim cannot disable loaded plugins.  It is Vim's feature.

**Comment by symbolix** [comment]
Thank you very much. One final thing, in relation to these, I have been trying to understand concepts such as:

    neobundle#tap
    neobundle#untap()
    neobundle#hooks.on_source(bundle)

I have been reading the documentation, which is really helpful, but is there some more information regarding these slightly more advanced *neobundle* features? (such as examples etc.)

Thank you very much for all the hard work and for the help.

**Comment by DeaR** [comment]
The settings for the lazy bundle is not required at the start of Vim.
It is required when sourcing.
```vim
if neobundle#tap('foo')
  function! neobundle#hooks.on_source(bundle)
    " Settings, Init, ...
    let g:foo#bar = 1
    let g:foo#path = a:bundle.path
    call foo#baz()
  endfunction
  " Mappings, Commands, ...
  map f <Plug>(foo)

  call neobundle#untap()
endif
```

**Comment by symbolix** [comment]
Hi DeaR,

I am struggling to understand the functionality behind *neobundle#tap* and *neobundle#hooks*.

I kind of understand how the *lazy* workflow works. With the *lazy* workflow, you can initialize the plugin, but not activate it until a specific condition is met. And you can either activate the *lazy* plugin with a straight forward:

    autocmd FileType c,cpp NeoBundleSource someBundle

or define the trigger event with the neobundle options, using *NeoBundleLazy*:

    NeoBundleLazy 'someBundle', {
        \ 'autoload' : {
        \     'filetypes' : ['c', 'cpp'],
        \    },
        \ }

or directly set those triggers with the *config* function:

NeoBundle 'someBundle'
    call neobundle#config('someBundle', {
        \ 'lazy' : 1,
        \ 'autoload' : {
        \    'filetypes' : ['c', 'cpp'],
        \ }})

So I understand all of these. What I do not understand is where *neobundle#tap* and *neobundle#hooks* stands in this situation? Could you please help me with this?

Thanks.

**Comment by Shougo** [comment]
Thanks.  I have improved neobundle#tap() example.

> So I understand all of these. What I do not understand is where neobundle#tap and neobundle#hooks stands in this situation? Could you please help me with this?

It is for plugin initialization.
`neobundle#tap()` is used to initialize plugin configuration if it is installed.
`neobundle#hooks` is syntax sugar of `neobundle#config().hooks`.
It is used for lazy plugins to initialize plugin after plugins are loaded.

**Comment by Shougo** [comment]
@symbolix neobundle supports advanced plugins initialization feature like `neobundle#tap()`.
This feature is not supported in other plugin management system.

**Comment by DeaR** [comment]
```vim
NeoBundleLazy 'foo/foo'
if neobundle#tap('foo')
  " Error
  " Cannot be called, because it does not exist in rtp.
  " Not necessary at Vim startup.
  " call foo#init()

  function! neobundle#hooks.on_source(bundle)
    " OK
    " Necessary if active only.
    " It can be shortened also the Vim startup time.
    call foo#init()
  endfunction

  call neobundle#untap()
endif
```
NeoBundle have powerful features.
The syntax sugar have a lot, So the setting way is a lot.

**Comment by symbolix** [comment]
Thanks guys, this was all very helpful. All these stages has to take place between the *neobundle#begin()* and *neobundle#end()* or *neobundle#append()*?

And one final question, when should I use this workflow?

    let bundle = neobundle#get('foo')
    function! bundle.hooks.on_post_source(bundle)
	  " Some settings.
    endfunction

and when I should use the *tap*/*untap* approach?

And when using the *tap*/*untap* workflow, should I still need this?

    let bundle = neobundle#get('foo')

between the #tap and #untap blocks?

Once again, thank you.

**Comment by DeaR** [comment]
> Thanks guys, this was all very helpful. All these stages has to take place between the neobundle#begin() and neobundle#end() or neobundle#append()?

It's better.
The non-lazy bundle's on_source called at the neobundle#end.
Is easy change of lazy If using a on_source in all of the bundle

> And one final question, when should I use this workflow?
> ```vim
let bundle = neobundle#get('foo')
function! bundle.hooks.on_post_source(bundle)
  " Some settings.
endfunction
```
> and when I should use the tap/untap approach?

That's the syntax sugar.  Can also.
tap/untap was made in order to make it smart.

> And when using the tap/untap workflow, should I still need this?
> ```vim
let bundle = neobundle#get('foo')
```
> between the #tap and #untap blocks?

No.  it same of the neobundle#tapped.
But, It is used when you want to use the information for another bundle.
e.g.
```vim
NeoBundleLazy 'foo/foo'
NeoBundleFetch 'foo/bar'
if neobundle#tap('foo')
  function! neobundle#hooks.on_source(bundle)
    let foo#bar_path = get(neobundle#get('bar'), 'path', '')
  endfunction
  call neobundle#untap()
endif
```

**Comment by symbolix** [comment]
Hi,

This is amazing help. Thank you very much. One final question: Is it OK to source other vim script files that contain neobundle commands between the *begin* and *end* blocks?

    " Start neobundle block
    call neobundle#begin(expand('~/.vim/bundle'))

    " Let neobundle manage neobundle
    NeoBundleFetch 'Shougo/neobundle.vim'

    " My Bundles here:
    exe 'source ' . somePlugin-init.vim
    exe 'source' . someOtherPlugin-init.vim
    ...

    call neobundle#end()

And, let's say, in the *somePlugin-init.vim* script file we have:

    NeoBundleLazy 'foo/somePlugin'
    if neobundle#tap('somePlugin')
        function! neobundle#hooks.on_source(bundle)
            call somePlugin#init()
        endfunction
    call neobundle#untap()
    endif

Will that setup work?

Thanks.

**Comment by Shougo** [comment]
> Will that setup work?

Yes.  It works.
