### ISSUE TITLE
"E121: Undefined variable: sourced" with NeoBundleReinstall

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#415]
I am getting an error when trying to reinstall a bundle:

In the second call to `neobundle#installer#update`, `a:bundles` is a simple list, and that causes errors:

    a:bundles ['Jinja2-Syntax']
    Error detected while processing function neobundle#commands#reinstall..neobundle#installer#reinstall..neobundle#installer#update:
    line   12:
    E121: Undefined variable: sourced
    Error detected while processing function neobundle#commands#reinstall..neobundle#installer#reinstall..neobundle#installer#update..<SNR>30_reload..neobundle#config#rtp_ad
    d:

Source reference: https://github.com/Shougo/neobundle.vim/blob/508db1afe01c703149ba045bedc6baae6f90890d/autoload/neobundle/installer.vim#L44-L45

This seems to have been introduced between 3726aa1 and 508db1a - I have noticed it after upgrading.

**Comment by Shougo** [comment]
Fixed.
