### ISSUE TITLE
NeoBundleDisable shouldn't disable some dependent bundles in some case

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#416]
Using -> to note dependencies
A -> B means A depends on B

Assume we have three bundles A, B, C
If A -> C, B ->C, disabling B using NeoBundleDisable will also disable C
But A also depends on C and this would result in some errors.

C should only be disabled only if all bundles depend on it are disabled.

**Comment by Shougo** [comment]
Implemented.
