### ISSUE TITLE
when lock to branch update does not work!

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neobundle.vim#422]
i use Neobundle 'userName/pluginName',''

**Comment by wsdjeg** [comment]
i use Neobundle 'userName/pluginName','branchName'
then NeobundleUpdate does not work

**Comment by Shougo** [comment]
I have tested the feature, and it works.
I think your usage/check is wrong

Please create minimal .vimrc less than 50 lines and upload reproduce ways from Vim starting.

**Comment by wsdjeg** [comment]
thank you  i find why
the plugin shows i am not on a branch
