### ISSUE TITLE
why can not update?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neobundle.vim#424]
/home/wsdjeg/.vim/bundle/vim-javacomplete2
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>
[neobundle/install] (12/81): |syntastic| Error
/home/wsdjeg/.vim/bundle/syntastic
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

[neobundle/install] (46/81): |nerdtree| Error
/home/wsdjeg/.vim/bundle/nerdtree
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

**Comment by wsdjeg** [comment]
https://github.com/Shougo/neobundle.vim/issues/275

**Comment by Shougo** [comment]
https://github.com/Shougo/neobundle.vim/issues/422

Please don't create dup issue.
