### ISSUE TITLE
Add link to github diff when updating bundles

### ISSUE THREAD

**Issue by mcagl** [Shougo/neobundle.vim#425]
Hi!
When I update my bundles, NeoBundle shows the short sha1sum of the last commit for every bundle it updated, and in the end it makes a "recap" with the names of the bundles that were actually updated.

It may be useful to add (for every updated bundle) a link to the "compare" view in github that shows the changes from the last commit before the update and the last commit after the update, ready to be clicked to help in reviewing of "what changed since I updated last time".

I said for the compare view in github because the 99% of my bundles are taken from github repositories.

**Comment by Shougo** [comment]
OK.  I will add the feature.

**Comment by mcagl** [comment]
Sorry, I did not see #166 before opening this issue, nor the fact that it's a hard to implement feature.

Thank you for the quick response!

**Comment by Shougo** [comment]
It is easy to just print github URI.

**Comment by Shougo** [comment]
Implemented.  Please test it.

**Comment by petobens** [comment]
Hi @Shougo, it is nice to have the URL printed once the update finishes. However I was wondering if it possible to add a Unite action to jump directly from the `:Unite neobundle/update` source to the URL? Currently I yank the URL and copy it to my browser.  For instance if the `:Unite neobundle/update` buffer displays:

```
Updated bundles:
neobundle
https://github.com/Shougo/neobundle.vim/compare/6b656b3947b9583534ae5f18b42976eac86204d6...9ef5236604e1e5332ddd7f9989d031b2de86b04c
```

It would be nice if I could just hit `<CR>` when selecting the candidate `neobundle` and have the Github diff URI opened in my browser.

**Comment by Shougo** [comment]
@petobens This feature is already implemented.
You can just press`<CR>` on URI.

**Comment by petobens** [comment]
Ohh I see. I wonder if it is possible to change the behavior in two ways:

i) when I press `<CR>` on the URI the Unite buffer closes. Can it be left open? I use the following mapping:
```vim
nnoremap <Leader>bu :Unite -no-start-insert -log neobundle/update:all<cr>
```

ii) This is purely aesthetics: Is it necessary to actually print the URI? Can the link be hidden/attached to the candidate name? This means I think it be nice to have the buffer like this:

```
Updated bundles:
neobundle
unite
```
(without the URI) and by selecting the candidate (`neobundle` or `unite`) and pressing `<CR>` jump to the URI (whenever the URI exists).

**Comment by Shougo** [comment]
> i) when I press `<CR>` on the URI the Unite buffer closes. Can it be left open? I use the following mapping:

Please update unite.vim.

> ii) This is purely aesthetics: Is it necessary to actually print the URI? Can the link be hidden/attached to the candidate name? This means I think it be nice to have the buffer like this:

I improved it.

**Comment by petobens** [comment]
Thank you!

**Comment by mcagl** [comment]
Thank you @Shougo, this is exactly what I had in mind!
