### ISSUE TITLE
neobundle#config doesn't work

### ISSUE THREAD

**Issue by pocke** [Shougo/neobundle.vim#427]
I use neobundle, neocomplete and neco-look.
However neco-look doesn't work with latest(dd5208f9a7c60e9dd311b5a91d30e5367acece42) neobundle.
I investigate this problem, and I think `neobundle#config` doesn't work.

minimal vimrc

```vim
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundle 'Shougo/neocomplete'
call neobundle#end()
filetype plugin indent on     " Required!


if neobundle#tap('neocomplete')
  call neobundle#config({
  \   'depends': ['ujihisa/neco-look'],
  \ })

  let g:neocomplete#enable_at_startup = 1
  call neocomplete#custom#source('look', 'min_pattern_length', 1)
  call neobundle#untap()
endif
```

procedure for reproducing
------------

1. use the above vimrc
1. `cd ~/.vim/bundle/neobundle.vim`
1.  `vim README.md`
1. type `oin`

Not suggestion words by look.

![1443344413](https://cloud.githubusercontent.com/assets/4361134/10121983/bc146834-6541-11e5-9545-52b5b75e28cf.png)

And if `git checkout 45f7b63`, `neobundle#config` is enabled to work.

![1443344516](https://cloud.githubusercontent.com/assets/4361134/10121989/fe0d48e6-6541-11e5-8905-00510aeee2a9.png)

Or it is enabled to work by the following vimrc(with latest neobundle).

```vim
if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundle 'Shougo/neocomplete', {'depends': ['ujihisa/neco-look']}
call neobundle#end()
filetype plugin indent on     " Required!



  let g:neocomplete#enable_at_startup = 1
  call neocomplete#custom#source('look', 'min_pattern_length', 1)
  call neobundle#untap()
```

So, I think cause of this problem is 6f864288a1f559cc3128f828828e4180d9485935 commit(#419), and `neobundle#config` function.

**Comment by Shougo** [comment]
Fixed.

**Comment by pocke** [comment]
Thanks!
