### ISSUE TITLE
where should i add my filetype plugin indent on in the vimrc?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neobundle.vim#428]
i do not know why?
case one===>
autocmd Filetype java set onimifunc=javacomplete#Complete
autocmd Filetype jsp set onimifunc=javacomplete#Complete
filetype plugin indent on
java file onimfunc is javacompelte
jsp file is htmlcomplete
but
case two ===>
filetype plugin indent on
autocmd Filetype java set onimifunc=javacomplete#Complete
autocmd Filetype jsp set onimifunc=javacomplete#Complete

all of java jsp file onimifunc is javacomplette

**Comment by DeaR** [comment]
`$VIMRUNTIME/ftplugin/jsp.vim` is source `$VIMRUNTIME/ftplugin/html.vim`
`$VIMRUNTIME/ftplugin/html.vim` is set omnifunc

Create `.vim/after/ftplugin/jsp.vim`, or
move `autocmd FileType` after `filetype plugin indent on`.

```vim
" .vim/after/ftplugin/jsp.vim
set onimifunc=javacomplete#Complete
```
```vim
" .vimrc
filetype plugin indent on
autocmd Filetype java set onimifunc=javacomplete#Complete
autocmd Filetype jsp set onimifunc=javacomplete#Complete
```

This is not NeoBundle problem, is the specification of Vim's ftplugin
See `:autocmd Filetype`

**Comment by wsdjeg** [comment]
thank you  , after i fix my vimrc ,i have reallized maybe some ftpubin/jsp.vim in my vim74 dir source the html.vim and that will set my onimifunc!
thank you for help me
