### ISSUE TITLE
Watch the install process logs

### ISSUE THREAD

**Issue by jeaye** [Shougo/neobundle.vim#432]
I don't see a documented way of watching the install process for various bundles with real-time log updating. I'm using vimproc ([example config](https://gist.github.com/jeaye/f3fe48a55f4e6e81817a)) but I still block when installing plugins. Since I'm blocked, I might as well have a look at the progress of the install; can this be done?

Also, should I be blocking, or is vimproc not being setup properly?

**Comment by Shougo** [comment]
> Also, should I be blocking, or is vimproc not being setup properly?

If you don't want to block it, you must use unite interface.

**Comment by Shougo** [comment]
> Since I'm blocked, I might as well have a look at the progress of the install; can this be done?

OK.  I will test it.  It may be useful.

**Comment by jeaye** [comment]
On Sun, Oct 11, 2015 at 09:38:01PM -0700, Shougo wrote:
>      Also, should I be blocking, or is vimproc not being setup properly?
> 
>    If you don't want to block it, you must use unite interface.

Ah, got it. I'm not interested in using unite at this time, so I can deal with it blocking. Is unite also required to watch the log during the install?

**Comment by jeaye** [comment]
On Sun, Oct 11, 2015 at 09:38:47PM -0700, Shougo wrote:
>      Since I'm blocked, I might as well have a look at the progress of the
>      install; can this be done?
> 
>    OK. I will test it. It may be useful.

Ah, perfect. Thanks.

**Comment by Shougo** [comment]
Implemented.
