### ISSUE TITLE
Hide git branch output when installing

### ISSUE THREAD

**Issue by squarefrog** [Shougo/neobundle.vim#433]
I have a provisioning script I use to get a new computer setup, or update an existing computer. In this script I run the following line to setup all my bundles:

    vim -c "NeoBundleInstall!" -c "qa!"

This works great, but during updates I get the full `git log` which appears to make me have to view the whole change stack before it'll carry on. Is there a way to do a silent install? For example just show:

    [neobundle] (10/18) [=======  ] vim-ruby updated

Instead of the full `git log` ?

**Comment by Shougo** [comment]
Please update neobundle.

**Comment by squarefrog** [comment]
Amazing work. Thanks for such an awesome plugin @Shougu!

**Comment by petobens** [comment]
Not sure if this commit change it but now when using `:Unite neobundle/update` when a plugin get updated the short commit message is not longer shown. I think it is useful to see this commit message. Can you please restore the behavior? Thanks

**Comment by squarefrog** [comment]
In that case perhaps there's should be a `verbose` install flag?

By default the message is hidden, but if you really want output you can pass the flag `v` to show it?

**Comment by Shougo** [comment]
> Not sure if this commit change it but now when using :Unite neobundle/update when a plugin get updated the short commit message is not longer shown. I think it is useful to see this commit message. Can you please restore the behavior? Thanks

If you want to see the full log, you can use `:NeoBundleLog` or `:Unite neobundle/log`.
`:Unite neobundle/update` is not the feature for it.

> In that case perhaps there's should be a verbose install flag?

No.  It is not needed.

**Comment by squarefrog** [comment]
:+1: elegant solution!

**Comment by Shougo** [comment]
I have implemented the feature, because the full log feature is already implemented.

**Comment by petobens** [comment]
I don't want to see the full log just the short commit message. I find this short message useful to decide whether I want to open the URL with the full commit or not.

**Comment by Shougo** [comment]
Updated.

**Comment by petobens** [comment]
Thank you. However
i) Now when I press `<CR>` on `-> diff URI` nothing happens.
ii) When I use `:Unite neobundle/update:all` and `neobundle` is update the update process pauses and gives a message `Press Enter to continue` (or something like that regarding pressing Enter)

**Comment by Shougo** [comment]
Fix done.

**Comment by petobens** [comment]
Thank you.

**Comment by bootleq** [comment]
Now `unite neobundle/log` can show commit messages, for example

    |neosnippet| * d657c10 [22 hours ago] Improve indent

But `NeoBundleUpdatesLog` still not showing them.
Would you add the commit logs to `NeoBundleUpdatesLog` too?
I'm used to it and think it's very useful.

**Comment by Shougo** [comment]
OK.

**Comment by bootleq** [comment]
Thank you very much!
