### ISSUE TITLE
committia can't be lazy loaded

### ISSUE THREAD

**Issue by jeaye** [Shougo/neobundle.vim#434]
Since I'm still trying to figure out just how applicable neobundle's lazy loading is, I'm curious if this is supposed to work. Example (trivial) config: https://gist.github.com/jeaye/cfd57ba58e185e32ef7b

[committia](https://github.com/rhysd/committia.vim) works fine if eagerly loaded, but doesn't seem to do anything at all, if lazy loaded on the correct filetype. Do you have any insight as to why this may be and whether or not neobundle's lazy loading is meant to be this flexible?

**Comment by Shougo** [comment]
Unfortunatelly, commitia must be loaded before set gitcommit filetype.

**Comment by Shougo** [comment]
You should use autoload explorer feature.

```
  NeoBundleLazy 'rhysd/committia.vim', {
    \ 'autoload' : { 'explorer' : 1 },
  \ }
```

**Comment by Shougo** [comment]
Oh, committia does not work in explorer mode...

**Comment by jeaye** [comment]
@Shougo If committia doesn't work in explorer mode, we should be sure to remove this: https://github.com/Shougo/neobundle.vim/commit/f06d961e52324aea547fe601f3e87c6fce16ca1e#diff-8d267d6c141adebdb1edad333a8efc2eL1177

**Comment by Shougo** [comment]
@jeaye It is already removed.  Thanks.
