### ISSUE TITLE
Don't rebuild when nothing has been pulled

### ISSUE THREAD

**Issue by jeaye** [Shougo/neobundle.vim#436]
After running `:NeoBundleUpdate`, YCM is always rebuilding. This is cumbersome, since it takes quite a while to compile and sucks up a good deal of CPU.

My YCM-related [config](https://github.com/jeaye/vimrc/blob/master/config/completion.vim):

```viml
call neobundle#append()
  NeoBundle 'Valloric/YouCompleteMe', {
    \ 'build': {
      \ 'mac': './install.py --clang-completer --omnisharp-completer',
      \ 'unix': './install.py --clang-completer --omnisharp-completer',
    \ },
  \ }
call neobundle#end()
```

Is this expected? If so, why?

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.
