### ISSUE TITLE
vim startup statistics

### ISSUE THREAD

**Issue by hyiltiz** [Shougo/neobundle.vim#437]
I have created a set of simple scripts that deal with startup timing. The raw vim log output has timing for each function call, but not for each plugins. So doing a simply statistics would be great. This is written in bash (and awk, sed, grep) along with R:ggplot2 package. It would be great if you could mention this project on the lazy-loading and optimization suggestions for your project. Would that be possible?

https://github.com/hyiltiz/vim-plugins-profile

**Comment by Shougo** [comment]
Thanks.  I have added it.

**Comment by hyiltiz** [comment]
Great! I will keep the young fun project alive and kicking .
On Tue, Oct 20, 2015 at 7:34 AM Shougo <notifications@github.com> wrote:

> Thanks. I have added it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shougo/neobundle.vim/issues/437#issuecomment-149534111>
> .
>
-- 
from Google Inbox
