### ISSUE TITLE
Error when updating unite spell-suggest source

### ISSUE THREAD

**Issue by petobens** [Shougo/neobundle.vim#438]
Consider the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

if has('vim_starting')
    execute 'set runtimepath+=' . expand('$DOTVIM/bundle/neobundle')
endif
call neobundle#begin(expand('$DOTVIM/bundle/'))
let g:neobundle#enable_name_conversion = 1
NeoBundleFetch 'Shougo/neobundle.vim', {'name' : 'neobundle'}
NeoBundle 'Shougo/unite.vim'
NeoBundle 'kopischke/unite-spell-suggest', {'lazy' : 1,
        \ 'unite_sources' : ['spell_suggest'] }
call neobundle#end()
```

Now open Gvim and run `:Unite neobundle/update:all`. I then get the following error when the update process completes:

```
(3/3): |unite-spell-suggest| Error
C:/OD/Users/Pedro/vimfiles/bundle/unite-spell-suggest
fatal: Needed a single revision
Unable to find current revision in submodule path 'lib/vim-mklib'

Error installing bundles:
unite-spell-suggest
Please read the error message log with the :message command.

Helptags: done. 2 bundles processed
Completed.
```

Note: this might be a problem in `unite spell-suggest` source. @kopischke

**Comment by kopischke** [comment]
Well, I won’t say I can exclude for sure it’s an _unite-spell-suggest_ issue, what with Git submodules being the PITA they are, but seeing there has been no change to the submodule (ref or source) for 11 months and that you are the first to report an issue with it, I would be surprised.

**Comment by petobens** [comment]
@kopischke indeed uninstalling and reinstalling `unite-spell-suggest` seems to fix the problem. Sorry for all the noise.
