### ISSUE TITLE
Number of plugins in Unite neobundle source

### ISSUE THREAD

**Issue by petobens** [Shougo/neobundle.vim#439]
Not really sure if this is an issue or not but consider the following screenshot (obtained with `:Unite neobundle/update:all`):

![screenshot-23-10-2015_01-23-12](https://cloud.githubusercontent.com/assets/2583971/10684588/4ea36a46-7925-11e5-80e7-8cd163d9111e.png)

At the top it says I have 35 plugins and at the bottom that 30 plugins where processed. Why the difference?

**Comment by DeaR** [comment]
5 plugins is not have doc folder

**Comment by Shougo** [comment]
> 5 plugins is not have doc folder

Yes.  Closing.

**Comment by petobens** [comment]
OK thanks
