### ISSUE TITLE
More Verbose NeoBundleUpdatesLog

### ISSUE THREAD

**Issue by amadeus** [Shougo/neobundle.vim#440]
It used to be that `NeoBundleUpdatesLog` would show a list of the commits and their messages if there was a plugin update. I found this feature to be really useful after an update to check what has updated and to find out exactly what has changed, almost like a change log.

Now it simply shows very obtuse git data, like the commit hashes. Is there anyway to get this old functionality back? It was very useful.

**Comment by Shougo** [comment]
You can use `NeoBundleLog` for it.
Closing.

**Comment by amadeus** [comment]
Yeah, the does work, however it's SUUUUPER noisy and hard to find the parts that were updates.

NeoBundleUpdatesLog was much nicer, before anyways.

What was the reason for these changes, out of curiosity?

**Comment by Shougo** [comment]
OK.  I get it.  But it is already implemented in #443.
Please update neobundle.

**Comment by amadeus** [comment]
Awesome, looks great! Thanks so much, I really appreciate it!
