### ISSUE TITLE
Question: are there hooks available to run commands before and after repo clone/pull?

### ISSUE THREAD

**Issue by kyounger** [Shougo/neobundle.vim#443]
I would like to be able to run specific `git config [--global]` commands at various times:

1. Globally, prior to a plugin repo being cloned 
2. After a repo is cloned, but inside the context of that repo
3. Globally, after a repo is cloned (this could obviously be the same hook as #2)

Does neobundle provide these hooks?

**Comment by Shougo** [comment]
After clone/pull, you can execute the command by `build` feature.
But the before is not.
