### ISSUE TITLE
when open vimrc show me this error

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/neobundle.vim#444]
![2015-11-07 21-50-23](https://cloud.githubusercontent.com/assets/13142418/11015421/a6129420-8599-11e5-9499-a83bd7be9fef.png)

**Comment by wsdjeg** [comment]
fixed

**Comment by Shougo** [comment]
It is tlib's documentation problem.
neobundle just prints the documentation bug for users.

**Comment by wsdjeg** [comment]
yes,i just fixed it by uninstall tlib,thank you for tell me
