### ISSUE TITLE
'gui': 1 doesn't work

### ISSUE THREAD

**Issue by rhysd** [Shougo/neobundle.vim#445]
`'gui': 1` で指定しているプラグインが gVim でもロードされていないのですが，確認お願いできませんでしょうか．
`'gui' : 1` を取り除くと期待通りロードされます．`:echo has('gui')` はちゃんと 1 を返しているのは確認済みです．

再現方法は下記の通りです．

## 1. Setup `~/foo.vimrc`

```vim
" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
    if &compatible
        set nocompatible               " Be iMproved
    endif
    set runtimepath+=~/.vim/bundle/neobundle.vim
endif

" Use git protocol.
" let g:neobundle#types#git#default_protocol = 'git'

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleLazy 'altercation/vim-colors-solarized', {
            \ 'gui' : 1,
            \ }
" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!

" ...

call neobundle#end()

filetype plugin indent on       " Required!

" Installation check.
NeoBundleCheck

"...

if !has('vim_starting')
    " Call on_source hook when reloading .vimrc.
    call neobundle#call_hook('on_source')
endif
```

## 2. Start gVim

```sh
$ vim -g -u ~/foo.vimrc -U NONE
```

## 3. Try to use the plugin

```
:colorscheme solarized
```

Result is:

```
E185: Cannot find color scheme 'solarized'
```

## Environment

- OS: OS X 10.11.1
- MacVim: 7.4 p622
- neobundle: 10101eb

**Comment by Shougo** [comment]
OK.
確認します

**Comment by rhysd** [comment]
よろしくおねがいします．
ちなみに Ubuntu の gVim(7.4-p728) と restart.vim でも再現しました．

**Comment by Shougo** [comment]
最小構成を作って確認しましたが、問題は再現しませんでした。

* そもそも colorscheme は自動ロードできないので、自動ロードされないのが正しい。`:NeoBundleLazy` するべきではない。

* `'gui': 1` のあるなしに拘らず、私の環境では colorscheme を自動ロードできない。もちろん、`:NeoBundleSource` すればロードできる。

* restart.vim でも問題が再現するというのが不思議。私の環境では再現しない。

@rhysd さんのほうでもう一度手順を確認してもらえますか。

補足：ちなみに、`has('gui')`ではなく、`has('gui_running')`が正しいチェック方法です。

**Comment by rhysd** [comment]
了解です．
うーん，以前は `'gui': 1` でロードできていたような気もするんですが，気のせいかもしれないです．
とりあえず restart.vim の件ははっきりさせたいので，確認したらコメントします．
明日は時間が取れなさそうなので，今週中ぐらいに確認します．

**Comment by NigoroJr** [comment]
私の環境(Gentoo Linux, Vim 7.4.827とMac OS X 10.9.5, MacVim 7.4.898)ではcolorschemeの方は両方とも再現しました。restart.vimはどちらの環境も再現しませんでした。

**Comment by rhysd** [comment]
@NigoroJr 

ご確認ありがとうございます．

@Shougo 

すみません，restart.vim はちゃんとロードされますね．こちらの勘違いでした．
