### ISSUE TITLE
vimrc リロード時にエラー

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/neobundle.vim#446]
ある特定の条件を満たすと vimrc をリロードした際に以下のようなエラーが出ます

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function <SNR>4_configure_neobundle[7]..neobundle#end[1]..neobundle#config#final[24]..neobundle#call_hook[8]..neobundle#config#tsort[4]..<SNR>8_tsort_impl:
line    6:
E714: List required
Error detected while processing /Users/alisue/.homesick/repos/rook/home/.vim/gvimrc:
line   64:
E596: Invalid font(s): guifont=RictyForPowerline:h10
```

調べたところ `get(a:target, 'depends', [])` (https://github.com/lambdalisue/neobundle.vim/blob/10101ebc95c8d8109507c9d86e285075b9ccc3e8/autoload/neobundle/config.vim#L546) で帰ってくる値が文字列になっているために起こっているようです。
そのため該当部分を以下のように修正すると治ります。

```vim
  for depend in get(neobundle#init#_bundle(a:target), 'depends', [])
```

ただ、これっておかしいはずですよね。本来この位置では init がかかった `a:target` が渡されてきているはずなので・・・原因を追うためにいろいろ見たのですがお手上げです。上記に「ある条件」と書きましたが、全条件を把握できていないため minimum vimrc もかけない状態です。
唯一確定している条件（最小限必要な条件ではなく、これがないと再現しなかったという意味）が

1. `NeoBundle` でソースしたものに対して `neobundle#config({ 'depends': 'xxxx' }) のようにする。

だけです orz ちなみに文字列じゃなくて `'depends': ['xxx']` のようにすると、次の行の `depend.name` で死にます。

回避方法は `depends` を `neobundle#config` で呼ばないだけなので、簡単なのですがワリとハマりポイントになっているので、お時間があるときに身ていただけると助かります。

**Comment by Shougo** [comment]
了解です。ちょっと根が深そうな問題ですね。
コードを確認します。

**Comment by lambdalisue** [comment]
ありがとうございます。他に報告がないことから環境依存型のバグだと思います…...本当に申し訳ないです。

ちなみに先ほど気が付きましたがリロードにより問題が 100% 再現する部分を消したものでも稀に再現することがわかりました（リロード後しばらく使用した後）。これも再現条件はわかりません orz 再現した場合プラグインの初期化がおかしくなり VimFiler などにも影響を及ぼしてエラーが大量発生してどうしようもならなくなります。

100% 再現していた際の vimrc などを貼っておきます。まったくミニファイズされていないのでアレですが作者の勘「もしかして？」などがある場合の確認にお使いください。リンク順に読みこまれます。

- [.vim ディレクトリ](https://github.com/lambdalisue/rook/tree/b50d8168f857c7b41efe821e656066ff776ead84/home/.vim)
- [.vimrc](https://github.com/lambdalisue/rook/blob/b50d8168f857c7b41efe821e656066ff776ead84/home/.vim/vimrc)
- [neobundle の有効化](https://github.com/lambdalisue/rook/blob/b50d8168f857c7b41efe821e656066ff776ead84/home/.vim/rc/plugin.vim)
- [各プラグインの宣言](https://github.com/lambdalisue/rook/blob/b50d8168f857c7b41efe821e656066ff776ead84/home/.vim/rc/plugin.define.vim)
- [各プラグインの設定(リンク範囲のコメントアウトを外すと100%再現)](https://github.com/lambdalisue/rook/blob/b50d8168f857c7b41efe821e656066ff776ead84/home/.vim/rc/plugin.config.vim#L671-L675)

**Comment by Shougo** [comment]
手元で再現しました。修正したので確認ください。

**Comment by lambdalisue** [comment]
な　ん　だ　と

修正確認しました。まさかこんな早く治るとは…ありがとうございました。

**Comment by lambdalisue** [comment]
autoload がおかしくなるようなのでメモ。詳細にわかったら追記します。

`autoload: { commands: 'Foo' }` などのばあい `Foo` を呼び出さずにリロードしてから `Foo` を呼び出すとオートロードされない。

**Comment by lambdalisue** [comment]
まとめました。 `&runtimepath` がリセットされるようです。 https://github.com/Shougo/neobundle.vim/issues/447

**Comment by Shougo** [comment]
エンバグしたので修正を一度 Revert しました。
最新版ではこの問題はないはずです。

**Comment by lambdalisue** [comment]
ありがとうございます！後で確認してみます
