### ISSUE TITLE
&runtimepath is not saved after reloading vimrc

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/neobundle.vim#447]
### Problem

`&runtimepath` is refreshed after reloading vimrc but functions / commands are not cleared thus `autoload` feature of neobundle is not triggered.

### minimum vimrc

```vim
set nocompatible

" For reloading Vimrc
if has('vim_starting')
  function s:reload_vimrc()
    execute printf('source %s', expand('~/vimrc.min'))
    redraw | echo 'vimrc has reloaded.'
  endfunction
endif
nnoremap <silent> ;;r :<C-u>call <SID>reload_vimrc()<CR>

" For showing current runtimepath
function! ShowRuntimePath()
  echo join(split(&runtimepath, ','), "\n")
endfunction


let bundle = expand('~/.vim/bundle')
if has('vim_starting')
  execute printf('set runtimepath+=%s', bundle . '/neobundle.vim')
endif

call neobundle#begin()
NeoBundleLazy 'lambdalisue/vim-gita'
if neobundle#tap('vim-gita')
  call neobundle#config({
        \ 'autoload': {
        \   'commands': 'Gita',
        \ }
        \})
endif
call neobundle#end()
if !has('vim_starting')
  call neobundle#call_hook('on_source')
endif
filetype plugin indent on
syntax on
```

### Procedure

1. `vim -N -u ~/vimrc.min`
2. Check `vim-gita` is not in `&runtimepath` via `:call ShowRuntimePath()`
3. Run `:Gita` to trigger 'autoload' feature of neobundle
4. Check `vim-gita` is in `&runtimepath'
5. Hit `;;r` to reload vimrc
6. Check `vim-gita` is **NOT** in `&runtimepath` (unexpected behaviour)
7. Calling autocmd of vim-gita cause error while it is not in '&runtimepath' but calling `:Gita` success while the command is alraedy defined thus 'autoload' feature of neobundle is not triggered.

**Comment by Shougo** [comment]
Fixed.
