### ISSUE TITLE
Overrides user FileType autocommands

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#452]
It seems that with Neobundle, the ftplugins are applied after any user `au FileType`, while you can influence the order in a minimal vimrc file, by configuring the autocommands before or after the `filetype plugin indent on`.

The doc is also unclear/wrong about how to use it with neobundle: https://github.com/Shougo/neobundle.vim/blob/master/doc/neobundle.txt#L1757-L1766.

`au FileType python echom "CUSTOM"` is always before the ftplugin.

**Comment by blueyed** [comment]
This happens because of `s:reset_ftplugin` being called.

**Comment by blueyed** [comment]
Maybe `reset_ftplugin` should take care to keep the order of `FileType` autocommands?

**Comment by Shougo** [comment]
Fixed.
