### ISSUE TITLE
Recent update breaks vba installation

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#453]
Error seen:

[neobundle] Path: http://www.drchip.org/astronaut/vim/vbafiles/Decho.vba.gz The protocol "http" is unsecure and invalid.
[neobundle] Path: http://www.drchip.org/astronaut/vim/vbafiles/Decho.vba.gz The protocol "http" is unsecure and invalid.
[neobundle] Path: http://www.drchip.org/astronaut/vim/vbafiles/Decho.vba.gz The protocol "http" is unsecure and invalid.
[neobundle] Failed parse name "http://www.drchip.org/astronaut/vim/vbafiles/Decho.vba.gz" and args {'lazy': 1, 'recipe': '', 'name': 'Decho', 'autoload': {'filetypes': ['vim'], 'commands': ['Decho']}, '
regular_namne': 'Decho', 'default': '_', 'script_type': 'vba'}

**Comment by Shougo** [comment]
It is intended behavior.

https://glyph.twistedmatrix.com/2015/11/editor-malware.html

You should not install the plugin from http protocol.

**Comment by paulhybryant** [comment]
Can we at least provide an option to allow installing from http?
People can use it at their own risk.
Thanks,

**Comment by Shougo** [comment]
No.  You can create the github repository for the vba.
You should download from it.
