### ISSUE TITLE
Neobundle force feature is not working after recent update

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#454]
Minimum vimrc to repro

set nocompatible                                                                " Must be first line
set encoding=utf-8                                                              " Set text encoding default to utf-8
scriptencoding utf-8                                                            " Character encoding used in this script
filetype off
let s:bundle_base_path = expand('~/.vim/bundle/')
execute 'set runtimepath+=' . s:bundle_base_path . 'neobundle.vim/'
call neobundle#begin(s:bundle_base_path)
NeoBundleFetch 'Shougo/neobundle.vim'                                           " Plugin manager
NeoBundle 'Shougo/neobundle-vim-recipes', { 'force' : 1 }                       " Recipes for plugins that can be installed and configured with NeoBundleRecipe
NeoBundle 'Rykka/os.vim', { 'force' : 1 }                                       " Provides consistency across OSes
let g:OS = os#init()
call neobundle#end()
filetype plugin indent on                                                       " Automatically detect file types.
NeoBundleCheck

NeoBundleList shows os.vim and neobundle-vim-recipes as disabled.

**Comment by paulhybryant** [comment]
It seems we should set bundle.sourced to 1 for force sourced bundle

diff --git a/autoload/neobundle/config.vim b/autoload/neobundle/config.vim
index a6bedc7..e752228 100644
--- a/autoload/neobundle/config.vim
+++ b/autoload/neobundle/config.vim
@@ -486,6 +486,7 @@ function! neobundle#config#add(bundle) "{{{

       if bundle.force
         runtime! plugin/**/*.vim
+        let bundle.sourced = 1
       endif
     endif
   elseif bundle.lazy

**Comment by Shougo** [comment]
Fixed.
