### ISSUE TITLE
Lazy behavior changed

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#455]
It seems after recent change, lazy will cause on_source hook to be called for the bundle, which doesn't seem to be the case in the past.

I am wondering what is the difference between autoload and lazy for a bundle? Doesn't autoload imply lazy?

**Comment by Shougo** [comment]
What's the problem?
I cannot understand your description.
Please describe it by the example.

**Comment by amerlyq** [comment]
@paulhybryant, autoload will affect only scripts located inside ```autoload/``` dir, loading all code from other dirs. So lazy loads much less, if only plugin's author wasn't trying to greatly reduce it's own startup time. Therefore for ```vim-altr``` it will not have much difference, when for most others would have.
As for on_source -- see loading order. If I'm not mistaken, currently it's like:
* vimrc + stuff inside neobundle#tap(...)
* bundle.on_source -- after adding to runtime but before actually sourcing plugin stuff (so functions from autoload/ could be called here.
* bundle.on_post_source

I think @Shougo will correct me if I'm mistaken.

**Comment by Shougo** [comment]
`bundle.hooks.on_source` and `bundle.on_post_source` are correct names.
Yes, the description is right.

**Comment by amerlyq** [comment]
Hm, so help file has mistake? There specified usage of ```bundle.hooks.on_post_source```. See:
```
NeoBundleLazy 'matchit.zip', { 'autoload' : { 'mappings' : ['%', 'g%'] }}
let bundle = neobundle#get('matchit.zip')
function! bundle.hooks.on_post_source(bundle)
    silent! execute 'doautocmd Filetype' &filetype
endfunction
```

**Comment by paulhybryant** [comment]
@Shougo Sorry for the late reply as I was in a trip. The problem is this:

In the past, I have the following in my config

NeoBundle 'foo/bar', { 'autoload' : { 'filetypes' : ['vim'] }, 'lazy' : 1 }
let s:foobar = neobundle#get('bar')
function s:foobar.hooks.on_source(bundle)
  let g:foobar_x = 1
endfunction

In the past, if the filetype I am editing is not of type vim, g:foobar_x will not be set.
However, after recent update, this behavior has changed, g:foobar_x will be set after opening vim, regardless of the filetype.

**Comment by paulhybryant** [comment]
@amerlyq Thanks for the reply but I am not quite following the explanation. I think autoload in neobundle means the plugin will be loaded when some conditions are satisfied (e.g. filetype = x)

From the example in the help:
NeoBundleLazy 'Rip-Rip/clang_complete'
autocmd FileType c,cpp NeoBundleSource clang_complete

This seems to be equivalent to
NeoBundle 'Rip-Rip/clang_complete', { autoload : { 'filetypes' : ['c', 'cpp'] }, 'lazy' : 1 }

**Comment by Shougo** [comment]
> In the past, if the filetype I am editing is not of type vim, g:foobar_x will not be set.
However, after recent update, this behavior has changed, g:foobar_x will be set after opening vim, regardless of the filetype.

OK.  If so, it is neobundle problem.
But I cannot reproduce the problem.
Please create minimal .vimrc within 20 lines and upload reproduce ways.

**Comment by Shougo** [comment]
> Also, everywhere in user configs used let neobundle#hooks.on_source = 'file'
> Never saw bundle.hooks.on_source used by anyone.

It is just syntax sugar of `bundle.hooks`.  It is not mistaken.
