### ISSUE TITLE
Enhance: command_prefix

### ISSUE THREAD

**Issue by amerlyq** [Shougo/neobundle.vim#457]
Make ```command_prefix``` to support ```List``` -- as for ```ag.vim``` it actually takes two prefixes, and some other plugins have non-consistent naming. Examples:
```
'command_prefix': ['Ag', 'LAg']
'command_prefix': ['GoldenView', 'ToggleGoldenView']
```

**Comment by Shougo** [comment]
`command_prefix` is not for it.

```
'commands': ['Ag', 'LAg']
'commands': ['GoldenView', 'ToggleGoldenView']
```

**Comment by amerlyq** [comment]
So you say I can't use ```command_prefix: Ag```  instead of fully-specified 
```commands: [Ag, AgAdd, AgBuffer, AgFile, AgFromSearch, AgGroup, AgHelp]```?
(And I similarly wanted second prefix for commands, started by ```LAg...```)
If it's the case, please, clarify its proper usecases in help.

**Comment by Shougo** [comment]
OK.  It seems new feature.

**Comment by Shougo** [comment]
Implemented it in the PR.  Please test it.
https://github.com/Shougo/neobundle.vim/pull/464
