### ISSUE TITLE
Bug: indirectly recursive neobundle#config#search

### ISSUE THREAD

**Issue by amerlyq** [Shougo/neobundle.vim#459]
To make function more robust and less errorprone, it would be nice to add that ```bundle_names``` are not contained in ```a:000```. Then recursion will stop after at most two steps and some meaningful message could be displayed or simply dropped further progression inside recursion. Case where that matters -- interconnected ```depends``` options. I have incidentally made neomru and unite depend on each other and couldn't find error without inserting echo inside neobundle.

**Comment by amerlyq** [comment]
Take a look inside your own dotfiles, you specified dependency on neomru inside unite recipe, when real dependency is inverse (according to help files in pluuregins). When such specification is not great deal and could be used as hack to force unite.vim fetch all linked plugins without explicitly configuring them all, in the future, when user will specify them explicitly inside vimrc and setup dependencies it will lead out to described behaviour (of course, user can somehow remember where that hack was, but...).

**Comment by Shougo** [comment]
Fixed.
