### ISSUE TITLE
How to initiate full init when lazy loading

### ISSUE THREAD

**Issue by amerlyq** [Shougo/neobundle.vim#460]
Plugin ```vim-gnupg``` consists of only one ```plugin.vim``` file, but greatly depends on mess of autocmd.
Is it possible to emulate it's complete loading when lazy? Using ```augroup``` key not helpful, because of plugin doesn't depend on ```VimEnter```. Manual init through ```doautocmd``` inside ```on_post_source``` hook did something half-harted -- see [#53](https://github.com/jamessan/vim-gnupg/issues/53).
Please, point out if this issue completely depends on plugin implementation or there are some details specific to NeoBundle.

**Comment by Shougo** [comment]
OK.  I get it.  You should use explorer feature.

```
NeoBundleLazy 'jamessan/vim-gnupg', { 'explorer': '*.\(gpg\|asc\|pgp\)' }

**Comment by amerlyq** [comment]
Same reaction in such configuration (I fixed regex: ```'.*\.\(gpg\|asc\|pgp\)$'```).
Hook on_post_source  (echo inside) is triggered when opening ```file.gpg```.
But without manual ```doautocmd``` no decryption was initiated -- so ```BufReadCmd``` wasn't sent to ```vim-gnupg``` automatically by using ```explorere``` feature.

**Comment by Shougo** [comment]
Added the support.

**Comment by amerlyq** [comment]
Maybe, it will fix some future problems with another plugins, but not with this one.
If I only specify ```NeoBundleLazy 'jamessan/vim-gnupg'```, open nvim, manually source plugin by ```:so ~/.cache/vim/bundle/vim-gnupg/plugin/gnupg.vim``` and then open file ```:e file.gpg``` -- all works.
But when I try use some NeoBundle autoload triggers -- like ```filename_patterns``` or ```explorer``` -- it's not. Besides, on usual file.gpg open routing (looking at logs of ```vim-gnupg```), BufReadCmd FileReadCmd wasn't called. So I have doubts it's right thing to do always.

**Comment by Shougo** [comment]
Did you test vim-gnupg with explorer in the latest neobundle?
OK.  I will test it.

Please upload minimal .vimrc and reproduce ways from Vim starting.

**Comment by amerlyq** [comment]
Yes, I tested with ```..., { 'explorer': '.*\.\(gpg\|asc\|pgp\)$' }``` -- your commit does same that I did manually in on_source hook yearlier and results in doubling output and incorrect work of ```vim-gnupg```.  Please, take a look in other side of this problem at [#53](https://github.com/jamessan/vim-gnupg/issues/53) -- there I have already published minimal vimrc to test by ```vim-gnupg``` author and I ask you to use the same one.

**Comment by amerlyq** [comment]
I assume you have installed and setted up gpg and have some encrypted file to test?
If not, you can refer to my step-by-step notes at [Initial Setup](https://github.com/amerlyq/airy/blob/master/cfg/net/gnupg/TODO.otl#L44) and [Encrypt Data](https://github.com/amerlyq/airy/blob/master/cfg/net/gnupg/TODO.otl#L195) at [cfg/net/gnupg](https://github.com/amerlyq/airy/tree/master/cfg/net/gnupg). I will render assistance to them, if necessary.

**Comment by Shougo** [comment]
OK.  I get the problem.  Please wait.

**Comment by Shougo** [comment]
Fixed.  But the fix is experimental.  It may be changed.

**Comment by Shougo** [comment]
Reverted.

You should use the feature.

```vim
autocmd BufReadCmd,FileReadCmd pattern NeoBundleSource vim-gnupg | doautocmd BufReadCmd
```

**Comment by chusiang** [comment]
Hi @Shougo,

I am a Vim user at Debian 7 (Wheezy), I can't see file context after upgrade the NeoBundle to 8dde1db.

I downgrade to f95ac5d and it's work, maybe you can help me? 

Attach my environment info:

    $ uname -a
    Linux thinkpad-t410 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux
    
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 7.9 (wheezy)
    Release:	7.9
    Codename:	wheezy

    $ /usr/bin/vim --version
    VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:28:00)
    Included patches: 1-547
    Modified by pkg-vim-maintainers@lists.alioth.debian.org
    Compiled by jamessan@debian.org
    Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
    +arabic +autocmd +balloon_eval +browse ++builtin_terms +byte_offset +cindent 
    +clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
    +conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con_gui +diff 
    +digraphs +dnd -ebcdic +emacs_tags +eval +ex_extra +extra_search +farsi 
    +file_in_path +find_in_path +float +folding -footer +fork() +gettext 
    -hangul_input +iconv +insert_expand +jumplist +keymap +langmap +libcall 
    +linebreak +lispindent +listcmds +localmap +lua +menu +mksession +modify_fname 
    +mouse +mouseshape +mouse_dec +mouse_gpm -mouse_jsbterm +mouse_netterm 
    -mouse_sysmouse +mouse_xterm +mouse_urxvt +multi_byte +multi_lang -mzscheme 
    +netbeans_intg +path_extra +perl +persistent_undo +postscript +printer +profile
     +python -python3 +quickfix +reltime +rightleft +ruby +scrollbind +signs 
    +smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
    +tag_old_static -tag_any_white +tcl +terminfo +termresponse +textobjects +title
     +toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
    +vreplace +wildignore +wildmenu +windows +writebackup +X11 -xfontset +xim 
    +xsmp_interact +xterm_clipboard -xterm_save 
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
          user exrc file: "$HOME/.exrc"
      system gvimrc file: "$VIM/gvimrc"
        user gvimrc file: "$HOME/.gvimrc"
        system menu file: "$VIMRUNTIME/menu.vim"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -pthread -D_REENTRANT -DORBIT2=1 -I/usr/include/libart-2.0 -I/usr/include/gconf/2 -I/usr/include/gnome-keyring-1 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/pango-1.0 -I/usr/include/gail-1.0 -I/usr/include/freetype2 -I/usr/include/atk-1.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gio-unix-2.0/ -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/libgnomeui-2.0 -I/usr/include/libgnome-2.0 -I/usr/include/libbonoboui-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/gnome-vfs-2.0/include -I/usr/include/orbit-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.5  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
    Linking: gcc   -L. -Wl,-z,relro -rdynamic -Wl,-export-dynamic  -Wl,-E  -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lglib-2.0     -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnomevfs-2 -lgnomecanvas-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lrt -lgobject-2.0 -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm  -L/usr/lib -llua5.1  -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.14/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib -ltcl8.5 -ldl -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by Shougo** [comment]
@chusiang Please upgrade to the latest version.  The commit is already reverted.

**Comment by chusiang** [comment]
@Shougo It's fixed, thank you very much. :+1:
