### ISSUE TITLE
neobundle fatal: unable to access 'https://github.com/tpope/vim-unimpaired.git/': Failed connect to github.com:443; Connecti on timed out

### ISSUE THREAD

**Issue by young2010** [Shougo/neobundle.vim#462]
I modify let g:neobundle#install_process_timeout=6000,
but when I run :neobundle in vim  it often display  "unable to accsee git and  timeout "Could I manual download vim pulgins in .vim/bundle?

**Comment by Shougo** [comment]
It is not neobundle problem.
It is just the network problem.  Closing.
