### ISSUE TITLE
Opening file from command line with vim <filename> opens an empty file

### ISSUE THREAD

**Issue by pshoukry** [Shougo/neobundle.vim#465]
**Steps to reproduce**
- update to latest version
```
vim filename.txt
```
**Reproducible**
Always

**Expected outcome**
opens the file

**Actual outcome**
opens an empty buffer with the filename

**Work around** 
revert to last commit in version 3.2

**Comment by Shougo** [comment]
Dup of https://github.com/Shougo/neobundle.vim/issues/463
