### ISSUE TITLE
Using neobundle-options-base_path to load externally installed bundles still prompts for bundle installation

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#466]
minimum vimrc to reproduce
"""""""""""""""""""""""""""""" VIMRC START """""""""""""""""""""""""""""""
set nocompatible

filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')

NeoBundleFetch 'Shougo/neobundle.vim'
let g:fzf_base_path = fnamemodify(system('brew --prefix fzf'), ':h')
NeoBundle 'junegunn/fzf', {
      \ 'base_path' : g:fzf_base_path,
      \ 'directory' : 'fzf',
      \ 'name' : 'fzf',
      \ 'regular_name' : 'fzf',
      \ }

filetype plugin indent on
call neobundle#end()
NeoBundleCheck
"""""""""""""""""""""""""""""" VIMRC   END """""""""""""""""""""""""""""""

You can replace the base path with an absolute value where fzf is installed.

**Comment by Shougo** [comment]
```vim
NeoBundle 'junegunn/fzf', {
\ 'base' : g:fzf_base_path,
\ 'directory' : 'fzf',
\ 'name' : 'fzf',
\ 'regular_name' : 'fzf',
\ }
```

You must use `base` instead of `base_path`.

**Comment by paulhybryant** [comment]
The help document still says base_path, I think it should be updated.

**Comment by Shougo** [comment]
Yes.  It will be updated soon.

**Comment by paulhybryant** [comment]
Thanks.
