### ISSUE TITLE
How to check if specific plugin exists before its settings

### ISSUE THREAD

**Issue by yusiwen** [Shougo/neobundle.vim#471]
Today I turned to NeoBundle from Vundle, thanks for your great work! Maybe it's a question irrelevant to NeoBundle, but it confused me for a real long time. Let me explain.

For example, I've 'NerdTree' installed and its settings below:

```
NeoBundle 'scrooloose/nerdtree'
....
" NerdTree settings {{{
  nnoremap <silent> <Leader>1 :NERDTreeToggle<CR>

  let g:NERDTreeChDirMode = 2
  let g:NERDTreeShowBookmarks = 1
  let g:NERDTreeWinPos = "left"
  let g:NERDTreeShowHidden = 0
" }}}
```

When I don't need 'nerd tree' in some circumstances, I comment out the line `NeoBundle 'scrooloose/nerdtree`, and I want to prevent the NerdTree settings to be executed in vimrc. Is that possible?

Thanks.

**Comment by kyounger** [comment]
Here's a good example from my vimrc:

https://github.com/kyounger/dotfiles/blob/master/vim/.vimrc#L971-L983

```vim
if neobundle#is_installed("name-of-plugin")
" do stuff...
end
```

**Comment by NigoroJr** [comment]
I use `neobundle#tap('plugin-name')`. From the docs:

```
neobundle#tap({bundle-name})			 *neobundle#tap()*
        Initialize |neobundle#tapped| and |neobundle#hooks| variable
        as {bundle-name} bundle.
        It returns non-zero if {bundle-name} is exists and not
        disabled.
```

Usage would be something like:

```vim
if neobundle#tap('nerdtree')
  nnoremap <silent> <Leader>1 :NERDTreeToggle<CR>

  " Only set variables right when NerdTree is sourced
  function! neobundle#hooks.on_source(bundle)
    let g:NERDTreeChDirMode = 2
    let g:NERDTreeShowBookmarks = 1
    let g:NERDTreeWinPos = "left"
    let g:NERDTreeShowHidden = 0
  endfunction

  call neobundle#untap()
endif
```

**Comment by kyounger** [comment]
Very interesting, I didn't know about #tap. Thanks.

**Comment by yusiwen** [comment]
It works, thanks a lot!
