### ISSUE TITLE
'depends' stopped working with tlib/tmru

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#474]
I've noticed that the 'depends' option failed on my server, when neobundle uses the cache.

I've bisected it to the following commit, but it does not happen always and therefore I've tried it ~5 times before marking a commit as good.

I am using this config, and 'tmru' will then fail because `loaded_tlib` does not exist.

    NeoBundle 'tomtom/tmru_vim' { 'depends': [['tomtom/tlib_vim', { 'directory': 'tlib' }]]}

> Error detected while processing /root/.dotfiles/vim/neobundles/tmru/plugin/tmru.vim:
line   13:
tlib >= 1.14 is required
Press ENTER or type command to continue

The `depends` should make sure that "tlib" gets loaded before "tmru" though.

```
commit a9ae08e9199fc98f564a3c012afde4823202d80f
Author: Shougo Matsushita <X>
Date:   Thu Nov 12 19:29:10 2015 +0900

    Remove force flag in neobundle#config#add()

diff --git a/autoload/neobundle/config.vim b/autoload/neobundle/config.vim
index f488a0e..de64d4e 100644
--- a/autoload/neobundle/config.vim
+++ b/autoload/neobundle/config.vim
@@ -450,18 +450,12 @@ function! neobundle#config#set(name, dict) "{{{
         \ neobundle#init#_bundle(extend(bundle, a:dict)))
 endfunction"}}}
 
-function! neobundle#config#add(bundle, ...) "{{{
+function! neobundle#config#add(bundle) "{{{
   if empty(a:bundle)
     return
   endif
 
   let bundle = a:bundle
-  let is_force = get(a:000, 0, bundle.local)
-
-  if !is_force && !bundle.overwrite &&
-        \     has_key(s:neobundles, bundle.name)
-    return
-  endif
 
   if !empty(bundle.depends)
     call s:add_depends(bundle)
```

It will work after `NeoBundleClearCache` on the next Vim startup, but then fails on the next restart.

**Comment by Shougo** [comment]
@blueyed I cannot reproduce the problem.
Please upload minimal .vimrc less than 20 lines and the reproduce ways from Vim starting.

**Comment by blueyed** [comment]
This is caused by "just" the wrong order in `&rtp`.

I cannot reproduce it using a minimal vimrc, where it ends up correctly as
`/tmp/neobundles/tlib/,/tmp/neobundles/tmru_vim/`:

```
set rtp+=~/.vim/bundle/neobundle
let s:bundles_path = expand('/tmp/neobundles')
call neobundle#begin(s:bundles_path)

filetype plugin indent on
if neobundle#load_cache($MYVIMRC)
  NeoBundle 'tomtom/tmru_vim', { 'depends': [['tomtom/tlib_vim', { 'directory': 'tlib' }]]}
  NeoBundleSaveCache
endif
call neobundle#end()
```

But with my vimrc I see that tlib gets added twice when the cache is used, and then for the 2nd addition the first one gets removed (relevant code: https://github.com/Shougo/neobundle.vim/blob/master/autoload/neobundle/config.vim#L456-L464).

**Comment by blueyed** [comment]
It seems like `neobundle#commands#save_cache` should sort the bundles, so that in this case `tlib` would come before `tmru`.

**Comment by blueyed** [comment]
See https://github.com/Shougo/neobundle.vim/pull/477 for a quick shot at fixing this.

**Comment by Shougo** [comment]
Fixed.
