### ISSUE TITLE
[Feature Request] Option to output sorted NeoBundleList

### ISSUE THREAD

**Issue by NigoroJr** [Shougo/neobundle.vim#475]
I often find myself staring at the output from `:NeoBundleList` for a while to see if the plugins that I want are properly sourced. I can use `:echo neobundle#is_sourced('plugin-name')` but it's nice to see output from `NeoBundleList` sorted by plugin name so that I can check multiple plugins at once. I'm thinking something along the lines of `:NeoBundleList -sort`. Do you think this is possible?

**Comment by Shougo** [comment]
OK.  Implemented.

**Comment by NigoroJr** [comment]
Looking great, thank you!
