### ISSUE TITLE
NeoBundleUpdate from shell command

### ISSUE THREAD

**Issue by FunTimeCoding** [Shougo/neobundle.vim#484]
I use a command to update bundles without starting vim: `vim --cmd "set t_ti= t_te=" +NeoBundleUpdate +q`, but since commit 41b2c06 the behavior seems to have changed, and the one prior 9e5c19a still seems to be working.

Before, I would see something like this:

```
[neobundle] Update started: (2016/01/03 16:41:42)
[neobundle] ( 1/29) [                    ] vim-rspec
[neobundle] ( 2/29) [=                   ] vim-phpqa
[neobundle] ( 3/29) [==                  ] python-mode
(and so on)
```

without the actual vim interface rendering, but now it does that. I found it more convenient the other way.

Was that intended?

**Comment by Shougo** [comment]
Fixed.

**Comment by FunTimeCoding** [comment]
Sweet, thank you!
