### ISSUE TITLE
Bundles still prompt for installation with NeoBundleFetch

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#485]
Say a bundle x depends on bundle y, if I understand correctly from the doc I can use NeoBundleFetch to register y, and NeoBundleCheck should not prompt for installing y?

**Comment by paulhybryant** [comment]
This is especially needed if y is a non-vim plugin, which is what NeoBundleFetch is for.

It seems that if I create an empty dir x in ~/.vim/bundle, the installation prompt goes away, but y can be a non-vim plugin installed somewhere else.

**Comment by paulhybryant** [comment]
Minimum vimrc to reproduce:

set nocompatible
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundleFetch 'davidhalter/jedi'
NeoBundle 'davidhalter/jedi-vim', {
  \ 'depends' : ['davidhalter/jedi'],
  \ }
NeoBundleCheck
call neobundle#end()
filetype plugin indent on

**Comment by Shougo** [comment]
> Say a bundle x depends on bundle y, if I understand correctly from the doc I can use NeoBundleFetch to register y, and NeoBundleCheck should not prompt for installing y?

No.  It installs y.
`NeoBundleFetch` does not add it to the 'runtimepath'.

**Comment by paulhybryant** [comment]
yes I understand it does not add it to rtp. I think that indicates the bundle is available somewhere else and NeoBundle should not try to install it? From the help documentation, the example is NeoBundleFetch 'davidhalter/jedi', if I use NeoBundleFetch to register it, but cannot use it in the dependencies, then what is the use case for NeoBundleFetch?

**Comment by Shougo** [comment]
> I think that indicates the bundle is available somewhere else and NeoBundle should not try to install it?

If so, you should specify the path.

> then what is the use case for NeoBundleFetch?

Most use case is to update neobundle by neobundle.
