### ISSUE TITLE
The bell will be rung when loading a textobj-plugin first time

### ISSUE THREAD

**Issue by toshi32tony3** [Shougo/neobundle.vim#486]
* Problems summary

テキストオブジェクトを拡張するプラグインの初回読み込み時に、ベルが鳴ります。
初回読み込み時のみで、その後は鳴らなくなります。

また、以下の設定をしている場合、初回読み込み時でもベルが鳴らなくなります。
```set belloff=esc```

また、neobundle.vimの以下の行をコメントアウトするとベルが鳴らなくなりました。
https://github.com/Shougo/neobundle.vim/blob/master/autoload/neobundle/autoload.vim#L143
上記処理前にmode(1)すると'no'が返ってきますが、L143-144をコメントアウトすると入力した処理が行われませんでした。\<Esc\>はオペレータ待機モードをキャンセルするために必要なはずでしたが、既にoperatorが握りつぶされていたものと思います。どこで握りつぶしていたかまでは追っていません。

* Environment Information
 * OS: Windows 7 64-bit
 * Vim version: GVim 7.4.1016

* Minimal vimrc less than 50 lines

```VimL
setglobal encoding=utf-8
scriptencoding utf-8

filetype plugin indent off

if has('vim_starting')
  if &compatible
    setglobal nocompatible
  endif
  setglobal runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle'))

NeoBundleLazy 'kana/vim-textobj-user'

NeoBundleLazy 'kana/vim-textobj-indent', {
      \   'depends' : 'kana/vim-textobj-user',
      \   'on_map'  : [['xo', 'ii', 'ai', 'iI', 'aI']],
      \ }

call neobundle#end()

filetype plugin indent on
```

* How to reproduce

 0. GVimを起動
 1. 適当なカーソル位置で```dii```と入力
 2. ベルが鳴り、カーソル位置と同インデントの行が削除される

**Comment by Shougo** [comment]
了解しました。私もこの処理の意図がよく分からないのですが、ESC を削除したので確認してください。
問題があったら戻すかもしれないです。

**Comment by toshi32tony3** [comment]
迅速な対応ありがとうございました。ベルが鳴る問題が解消されていることを確認しました。
この修正による問題が発生してしまった時は、また報告させていただきます。
