### ISSUE TITLE
NeoBundleDisable complains about Disabled bundles not found when it is actually sourced

### ISSUE THREAD

**Issue by paulhybryant** [Shougo/neobundle.vim#487]
minimum vimrc to reproduce:

set nocompatible
filetype off
set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
call neobundle#begin('$HOME/.vim/bundle')
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'DeaR/vim-scratch'
NeoBundleDisable vim-scratch
call neobundle#end()
NeoBundleCheck
filetype plugin indent on

I have tried NeoBundleDisable DeaR/vim-scratch also

**Comment by Shougo** [comment]
Fixed.

**Comment by paulhybryant** [comment]
Thanks for the fix. I have two questions.

1. Why do we need to use self to filter a:bundle_names? I don't quite understand the logic there (e.g. infinite loop)
2. This is not related but I am wondering how can we remove a dependency for a bundle. Say I use NeoBundleDisable to disabled bundle x, but y depends on x. How can I remove the dependency of x from y? This might be desirable because some functionality of y does not depend on x and I don't need those functionality.

**Comment by Shougo** [comment]
> Why do we need to use self to filter a:bundle_names? I don't quite understand the logic there (e.g. infinite loop)

It is to ignore same plugins.
Example: Plugin A depends B.  Plugin B depends A.
If you load A, B must ignore A loading.

> This is not related but I am wondering how can we remove a dependency for a bundle. Say I use NeoBundleDisable to disabled bundle x, but y depends on x. How can I remove the dependency of x from y? This might be desirable because some functionality of y does not depend on x and I don't need those functionality.

You cannot disable x.
Because, x is needed for y.
