### ISSUE TITLE
Use XDG_CACHE_HOME for cache files

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#488]
From http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html:

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

This would allow to easily exclude those in backups etc.

**Comment by Shougo** [comment]
Rejected.

You can change the `neobundle#begin()` path under $XDG_CACHE_HOME.
