### ISSUE TITLE
Use XDG_DATA_HOME for bundles in Neovim by default

### ISSUE THREAD

**Issue by ZyX-I** [Shougo/neobundle.vim#492]
According to the `neobundle#begin` documentation

> If {base-path} is omitted, neobundle looks for "~/.vim/bundle"
> or "~/.config/nvim/bundle" directory.

which is not XDG compliant because third-party plugins are not configuration. I would suggest using ~/.local/share/nvim/bundle (default path for third-party plugins installed by user is ~/.local/share/nvim/site, but I do not think adding /site before bundle is needed).

**Comment by Shougo** [comment]
I think user should not omit the argument.
Yes, the omit behavior is not XDG compatible.
But it is to keep the compatibility.
