### ISSUE TITLE
Cannot redefine function nobundle#autoload#_command: It is in use

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/neobundle.vim#494]
Exception occur at `autoload/neobundle/autoload.vim #87`. It seems a lazy loading by command execution has a bug.

### Min vimrc

```vim
set nocompatible

if has('vim_starting')
  execute printf('set runtimepath+=%s', expand('~/.vim/bundle/neobundle.vim'))
endif
call neobundle#begin(expand('~/.vim/bundle'))

NeoBundle 'Shougo/unite.vim', {
      \ 'on_cmd': 'Unite',
      \}

call neobundle#end()

syntax on
filetype plugin indent on
```

### How to re-produce
1. Start vim
2. Type `:Unite<CR>`

### Confirmed with
- neovim 
- GVim 7.4.1246

**Comment by Shougo** [comment]
Reproduced.  But it is not neobundle's bug.
It seems unite.vim's bug.
Please update unite.vim.

**Comment by lambdalisue** [comment]
ok. thanks:-)
