### ISSUE TITLE
Why on_unite feature has been deleted?

### ISSUE THREAD

**Issue by delphinus35** [Shougo/neobundle.vim#495]
I found 57a1ec118ac73ca033aa8c2dc98d71986a3272ac has deleted the feature. Can I get the same feature by other option keys?

**Comment by Shougo** [comment]
Yes, I have removed.

Because,

* the implementation is too complex.  Unite must call neobundle functions.

* It is only useful in unite.vim

You should use `on_source` feature instead of `on_unite`.

`{'on_source': 'unite.vim'}`

**Comment by delphinus35** [comment]
thx for reply. I can get lazy loading unite-xxx with unite sourcing
