### ISSUE TITLE
Invalid runtimepath is detected in Windows

### ISSUE THREAD

**Issue by ClaudiaJ** [Shougo/neobundle.vim#497]
Setting RTP with the following snippet:
```vim
  let &runtimepath = join([
        \ expand('$XDG_CONFIG_HOME/vim'),
        \ expand('$VIM/vimfiles'),
        \ expand('$VIMRUNTIME'),
        \ expand('$VIM/vimfiles/after'),
        \ expand('$XDG_CONFIG_HOME/vim/after')], ',')
```

`echo expand('$VIMRUNTIME')` outputs `C:/Program Files/Vim/vim74`

`echo $VIMRUNTIME` outputs `C:\Program Files\Vim\vim74`

The error is being triggered for this code:
```vim
let n = index(rtps, $VIMRUNTIME)
```

Because `$VIMRUNTIME` doesn't actually match any value in `rtps`, due to the difference between `\` and `/`, plugin fails, despite technically valid runtimepath.

Temporary workaround is to add the following to vimrc before neobundle is called:
```vim
let $VIMRUNTIME=expand('$VIMRUNTIME')
```

**Comment by Shougo** [comment]
@ClaudiaJ I think `expand()` does not convert backslash.
Have you set `shellslash` option?

I think it is your configuration problem.  I don't recommend to set path manually.

**Comment by ClaudiaJ** [comment]
Whoops, you are right.

I mostly copied your dotfiles. I preferred `shellslash` on, but commenting that out makes the problem go away.
