### ISSUE TITLE
unite_sources is broken

### ISSUE THREAD

**Issue by taohex** [Shougo/neobundle.vim#499]
Using `NeoBundleLazy` with `unite_sources` doesn't work in new version. I also tested on an old version, it works.

```sh
nnoremap <silent> [unite]b :<C-u>Unite -auto-resize -buffer-name=buffers buffer file_mru<CR>
NeoBundleLazy 'Shougo/neomru.vim', {'autoload':{'unite_sources':'file_mru'}}
```

**Comment by taohex** [comment]
Message:
```
[unite.vim] Invalid source name "file_mru" is detected.
[unite.vim] To use MRU features, you must install neomru from https://github.com/Shougo/neomru.vim.
[unite.vim] unite.vim: Invalid source
```

**Comment by wsdjeg** [comment]
please read the message before open an issue .you does not install `Shougo/neomru.vim`

**Comment by taohex** [comment]
I have installed `Shougo/neomru.vim`. And when I change the second line to `NeoBundle 'Shougo/neomru.vim'`, it works fine. It's broken only when I use `NeoBundleLazy`.

**Comment by wsdjeg** [comment]
can you show me the minivimrc? I will test for it

**Comment by taohex** [comment]
set nocompatible
set all& "reset everything to their defaults
set rtp+=~/.config/nvim/bundle/neobundle.vim
call neobundle#begin(expand('~/.config/nvim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/unite.vim' "{{{
        let bundle = neobundle#get('unite.vim')

        function! s:unite_settings()
                nmap <buffer> Q <Plug>(unite_exit)
                nmap <buffer> <Esc> <Plug>(unite_exit)
                imap <buffer> <Esc> <Plug>(unite_exit)
        endfunction
        autocmd FileType unite call s:unite_settings()

        " -auto-preview
        nnoremap <silent> <Space><Space> :<C-u>Unite -toggle -auto-resize -buffer-name=mixed buffer file/async:! file_mru bookmark<CR><C-u>
        nnoremap <silent> <Space>l :<C-u>Unite -auto-resize -buffer-name=line line<CR>
        nnoremap <silent> <Space>b :<C-u>Unite -auto-resize -buffer-name=buffers buffer file_mru<CR>
"}}}

" case 1: error
NeoBundleLazy 'Shougo/neomru.vim', {'autoload':{'unite_sources':'file_mru'}}
" case 2: correct
"NeoBundle 'Shougo/neomru.vim'

call neobundle#end()
filetype plugin indent on
syntax enable

NeoBundleCheck

" Please use this as `~/.config/nvim/init.vim` for test

**Comment by wsdjeg** [comment]
I can confirm this issue ,even if `:Unite file_mrc` show same error

**Comment by Shougo** [comment]
This feature "unite_sources" are removed.
Please use `'on_source': 'unite.vim'` instead.

**Comment by wsdjeg** [comment]
thanks

**Comment by taohex** [comment]
Thanks. But should I change the line like this?

```sh
NeoBundleLazy 'Shougo/neomru.vim', {'autoload':{'on_source':'unite.vim'}}
```

This seems not work.

**Comment by taohex** [comment]
I figured out this. I have to change `unite.vim` to `NeoBundleLazy` altogether.

```sh
NeoBundleLazy 'Shougo/unite.vim', {'autoload':{'commands':['Unite','UniteWithBufferDir','UniteWithCurrentDir','UniteWithProjectDir','UniteWithCursorWord']}}
" In order to enable neomru, we have to use NeoBundleLazy on unite.vim
NeoBundleLazy 'Shougo/neomru.vim', {'autoload':{'on_source':'unite.vim'}}
```

This code works.

**Comment by Shougo** [comment]
@taohex
It is feature.  Because, it no means to load for the not lazy plugin.
on_source is for lazy plugins feature.
