### ISSUE TITLE
github login is necessary to download packages?

### ISSUE THREAD

**Issue by kierun** [Shougo/neobundle.vim#502]
I tried to install NeoMake via `NeoBundle "penekastah/neomake"` then running `nvim`.  It prompts me to decide if I want to install NeoMake, if I say yes I get a pop up asking for my github username and password.

Why would I need to login to github to download something?

Furthermore, the GUI box steals focus which is _really bad design_.

I am running NVIM 0.1.2 and the latest neobundle.

**Comment by kierun** [comment]
Okay, I found the error: It should be `NeoBundle "benekastah/neomake"`, not `NeoBundle "penekastah/neomake"` -- notice the b becomes a p in the wrong version.

Still, that is a weird effect for such an error.

**Comment by Shougo** [comment]
neobundle development is done.
it is wired error though.
I will fix it in dein.vim

**Comment by Shougo** [comment]
> Furthermore, the GUI box steals focus which is really bad design.

Please read `f` flag in `:help guioptions`.
