### ISSUE TITLE
Question: lazyload with an exact file name

### ISSUE THREAD

**Issue by chenhouwu** [Shougo/neobundle.vim#503]
I have a plugin  `direnv/direnv.vim`, I want to **lazily** enable it on file with exact the name `.envrc`.
How I should config?
Thanks!

**Comment by Shougo** [comment]
`'on_path': '.envrc'`

**Comment by chenhouwu** [comment]
None of the following two configs works 
```
 NeoBundleLazy 'direnv/direnv.vim', {'autoload':{'on_path': '.envrc'}}
```
```
 NeoBundleLazy 'direnv/direnv.vim', {'on_path': '.envrc'}
```

**Comment by Shougo** [comment]
I cannot reproduce it.

```
set nocompatible

set runtimepath+=~/work/neobundle.vim/

call neobundle#begin(tempname())
NeoBundleLazy 'direnv/direnv.vim', {'on_path': '.envrc'}
call neobundle#end()
```

direnv.vim is loaded after editing `.envrc`.
Why do you think `None of the following two configs works`?
I have not ESP skill.  Please explain it.

**Comment by wsdjeg** [comment]
@chenhouwu  neobundle can not filter all files in your computer,it just filter the file you edit.
@Shougo I think he want this feature.
if there is `.envrc` in the root diretory of his project,he want load the plugin,otherwise this plugin should not be load.
but `on_path` is for filter buffer name ,see doc:
on_path		(String) or (List)
		If set to ".*", neobundle will |:NeoBundleSource|
		on editing all files.
		Otherwise, neobundle will |:NeoBundleSource| if the
		buffer name is matched the string pattern.
		Note: It is useful for explorer behavior plugins.
		Ex: vimfiler, metarw, vim-gnupg ...
		Note: To autoload vimfiler, you must disable netrw in
		.vimrc. >
		" Disable netrw.vim
		let g:loaded_netrwPlugin = 1
<
		For example: >
		NeoBundle 'kana/vim-meta', {
		\ 'on_path' : '\h\w*:',
		\ }
<

**Comment by wsdjeg** [comment]
I think you should use dein.vim,also wrote by Shougo;
then you can add 
```vim
call dein#add( 'kana/vim-meta' ,  { 'if' : 'filereadable(".envrc")' })
```
also you can other check func, such as findfile() or finddir(). for more info see help doc

**Comment by chenhouwu** [comment]
@wsdjeg Nope, I just want to enable the plugin when I am editing ".envrc", rather than enable the plugin when the file exists.
What should I do?

**Comment by chenhouwu** [comment]
@wsdjeg Nope, I just want to enable the plugin when I am editing ".envrc", rather than enable the plugin when the file exists.
What should I do?

@Shougo 
when I load the plugin **not** the lazy way, see the following config
![qq20160421-4](https://cloud.githubusercontent.com/assets/1224321/14697913/42b3fffa-07bb-11e6-81ba-1db817f8d40d.png)

then when I open a `.envrc` file, I see
![qq20160421-2](https://cloud.githubusercontent.com/assets/1224321/14697917/54a5d1d4-07bb-11e6-8ca0-6ef405044835.png)

which indicates the plugin is loaded.

---

When I load the plugin the lazy way, see the following config
![qq20160421-0](https://cloud.githubusercontent.com/assets/1224321/14697923/64ae9548-07bb-11e6-93eb-c275af4f34f7.png)

then when I open a `.envrc` file, I see
![qq20160421-3](https://cloud.githubusercontent.com/assets/1224321/14697928/728afaa8-07bb-11e6-8fde-6750e459ac14.png)

which indicates the plugin **is not** loaded.

**Comment by chenhouwu** [comment]
@wsdjeg Wow, never know the `dein` plugin manager. 
Is it the next generation of `Neobundle`?
Should `dein` be preferred to `Neobundle`?

**Comment by wsdjeg** [comment]
please see neobundle readme

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by chenhouwu** [comment]
works, thanks!
