### ISSUE TITLE
Allow to specify/override neobundle#get_rtp_dir

### ISSUE THREAD

**Issue by blueyed** [Shougo/neobundle.vim#504]
I am using different cache keys / files for `g:neobundle#cache_file` depending on the environment, and that helps with loading in general, but helptags will be rebuilt then always.

Would it help to being able to set a tags dir (used by `neobundle#get_tags_dir()`) for that?
(i.e. having a `doc` dir for each cache file / variant).
I could imagine setting a cache dir (instead of a file), which would be used for the cache and the `doc` then: basically allow to configure what `neobundle#get_rtp_dir()` returns and use this everywhere (instead of `neobundle#get_neobundle_dir() . '/.neobundle'`.

**Comment by Shougo** [comment]
neobundle development is done.
I don't want to add new feature.
