### ISSUE TITLE
readme.mdのコマンドが実行できない

### ISSUE THREAD

**Issue by lv7777** [Shougo/neobundle.vim#506]
> If you want to install manually or you are using Windows.

>    Setup NeoBundle:

>     $ mkdir -p ~/.vim/bundle
>     $ git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

で`mkdir -p ~/.vim/bundle`を実行するものの、`コマンドの構文が誤っています。`と出ます。

___
# environment

* windows 10
* vim kaoriya版

**Comment by lv7777** [comment]
pスイッチがwindowsには無いそうです。

**Comment by Shougo** [comment]
Fixed.
