### ISSUE TITLE
`on_path` is not working on second time

### ISSUE THREAD

**Issue by Milly** [Shougo/neobundle.vim#508]
`on_path` is only working first time.
Because `augroup neobundle-path` is cleared, if all bundles does not match.

### example
```vim
" .vimrc
"...
NeoBundleLazy 'FilipDeVos/vim-msbuild', {'on_path' : '\.proj$'}
"...
```

1. Run `vim foo.txt`
2. Do ':e bar.proj'
3. But 'vim-msbuild' is not sourced.

**Comment by Shougo** [comment]
Fixed.

**Comment by Milly** [comment]
Works fine.
Thx! :+1:
