### ISSUE TITLE
Install includes extra step

### ISSUE THREAD

**Issue by trollkarlen** [Shougo/neobundle.vim#509]
Add this to readme.md about the .vimrc file and it will install automatic if not installed.
```
  if !filereadable(expand("~/.vim/bundle/neobundle.vim/README.md")) 
        let g:hasNeoBundle=1
                echo "Installing NeoBundle plugin"
                echo ""
                silent !mkdir -p $HOME/.vim/bundle
                silent !git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
  endif
```
/T

**Comment by Shougo** [comment]
I don't want to do it.

**Comment by trollkarlen** [comment]
Me neither but i would like it in the git :)

Its very nice if you use different computers a lot you can just copy the vimrc to the new one and start it and it fixes everything.

/R

**Comment by Shougo** [comment]
> Its very nice if you use different computers a lot you can just copy the vimrc to the new one and start it and it fixes everything. I know that usability is not the linux way but maybe this time we can make an exception :P

I don't want to add the script.
Because, the installation directory is different each people.
