### ISSUE TITLE
Unknown SSL protocol error in connection to github.com:443

### ISSUE THREAD

**Issue by light2yellow** [Shougo/neobundle.vim#510]
I'm getting this error pretty often. And it can happen to any bundle. Maybe vimproc's parallel downloads are causing this?
```
Update started: (2016/07/18 10:01:55)
(1/1): |neobundle.vim| git pull --ff --ff-only && git submodule update --init --recursive
(1/1): |neobundle.vim| Error
/home/alexey/.vim/bundle/neobundle.vim
fatal: unable to access 'https://github.com/Shougo/neobundle.vim/': Unknown SSL protocol error in connection to github.com:443
Helptags: done. 16 bundles processed

Error installing bundles:
  neobundle.vim
Please read the error message log with the :message command.

Update done: (2016/07/18 10:03:56)
```
`git` is fully functional and the only solution to this is doing everything manually.

**Comment by Shougo** [comment]
This is not neobundle problem.
It seems your environment problem.
You should search for `Unknown SSL protocol error `.

**Comment by light2yellow** [comment]
I did. This problem is not solved by anyone or solved in the ways that are already implemented on my side. I don't get this using git from console. I don't even get this constantly under neobundle. It happens with random bundle on random pull.

**Comment by Shougo** [comment]
http://stackoverflow.com/questions/20491027/unknown-ssl-protocol-error-in-connection

**Comment by Mukesh-AdvancedTicketing** [comment]
QATest - On continue click from "Confirm Delivery Address" is correctly expanding "Free Basket" accordion. Hence, this is no longer reproducible. More details needed to replicate the exact scenario.

**Comment by Shougo** [comment]
?
