### ISSUE TITLE
Mix of help file encodings within a language

### ISSUE THREAD

**Issue by syslot** [Shougo/neobundle.vim#512]
Hi,Shougo
    Just now, I installed [vim-devicons](https://github.com/ryanoasis/vim-devicons/) by neobundle and when it finished, NeoBundle said: 

`Vim(helptags):E670: Mix of help file encodings within a language: /xxx/.vim/bundle/.neobundle/doc/webdevicons.txt
`

Then some help tags could not used. Is this a bug?

**Comment by Shougo** [comment]
This is not neobundle bug.
It is just the tagfile error.
Closing.

**Comment by Shougo** [comment]
I think it is not actual fix or some Unicode chars are auto generated.
https://github.com/ryanoasis/vim-devicons/pull/163

**Comment by syslot** [comment]
Thank you for your answer .
- I have tried to update this plugin and it also showed the save error.
- Then I test plugin by other plugin manager tool,such as [vim-plug](https://github.com/junegunn/vim-plug) and it didn't show the tag error.

**Comment by Shougo** [comment]
https://github.com/ryanoasis/vim-devicons/blob/master/doc/webdevicons.txt

Current vim-devicons file has some of Unicode characters.
I think it is the problem.

Note:  You should create minimal vimrc.
You should check encodings.
Please upload your environment information.

**Comment by syslot** [comment]
Ok, thanks for your answer and I will try.
Here is my environment information.
- OS : Mac OS X v10.11.6
- vim: 7.4.2290 
- NeoBundle: 9c62a8fcf9eb42d3956c703943c99f06a63112e6
- vim-devicons: https://github.com/ryanoasis/vim-devicons/commit/cb15d791e2cc43457ef9abbed94efbf56a21bfc3

**Comment by Shougo** [comment]
> Note: You should create minimal vimrc.
> You should check encodings.

**Comment by Shougo** [comment]
I have reproduce it.

**Comment by Shougo** [comment]
> Then I test plugin by other plugin manager tool,such as vim-plug and it didn't show the tag error.

vim-plug does not merge the plugins.
If the plugin is only vim-devicons, no error.

**Comment by Shougo** [comment]
I get it.

vim-devicons documentation header has multibyte hyphen character.  It is invalid.

You should report it.  It should be fixed.
