### ISSUE TITLE
Duplicate tag ":UltiSnipsAddFiletypes"

### ISSUE THREAD

**Issue by HaleTom** [Shougo/neobundle.vim#513]
Thanks for a great plugin and all your work in keeping the issues down to zero! This is remarkable for a plugin of this complexity!

When updating my plugins just now, I get:
```
[neobundle] Error generating helptags:
[neobundle] Vim(helptags):E154: Duplicate tag ":UltiSnipsAddFiletypes" in file /home/ravi/.local/share/vim/bundle/.neobundle/doc/youcompleteme.txt
[neobundle] Update done: (2016/09/28 21:24:43)
```

Can NeoBundle handle it if there is a duplicate tag used in two different plugins?

**Comment by HaleTom** [comment]
I should mention that I'm also using `Unite`, should that make any difference.

**Comment by Shougo** [comment]
> Can NeoBundle handle it if there is a duplicate tag used in two different plugins?

The warning is *Vim* feature.
The plugin authors must not define duplicated tag.
I think YouCompleteMe or UltiSnips tag is wrong.
