### ISSUE TITLE
[vba] Unable to install bundle from local vimball file or vim.org link

### ISSUE THREAD

**Issue by Coacher** [Shougo/neobundle.vim#517]
Hello.

I have
```
call neobundle#begin('~/.vim/plugins/')
NeoBundle 'file://~/.vim/vimballs/ingo-library-1.027.vmb',
        \ {'name': 'ingo-library', 'type': 'vba', 'frozen': 1}
call neobundle#end()
```

I do `:NeoBundleUpdate!` and I get
```
|ingo-library| curl --fail -s -o "/home/coacher/.vim/plugins/ingo-library/" "" && vim -u NONE -c "set nocompatible" -c "filetype plugin on" -c "runtime plugin/gzip.vim" -
c "runtime plugin/vimballPlugin.vim" -c "edit /home/coacher/.vim/plugins/ingo-library/" -c "UseVimball /home/coacher/.vim/plugins/ingo-library" -c "q"
```

The correct path to the vimball is nowhere to be seen in the command neobundle uses.
This results in a non-functional plugin. I've also tried to use `'~/.vim/vimballs/ingo-library-1.027.vmb'`, but the problem persists.

vim is 8.0.0032, neobundle is master @  6d6900a.

Please fix.

**Comment by Coacher** [comment]
CC @paulhybryant

**Comment by Coacher** [comment]
I have exactly the same problem if I use the original vim.org link like this:
```
NeoBundle 'http://www.vim.org/scripts/download_script.php?src_id=24573',
        \ {'name': 'ingo-library', 'type': 'vba', 'frozen': 1}
```

**Comment by Shougo** [comment]
> I have exactly the same problem if I use the original vim.org link like this:

vim.org is http.
https is only supported.

**Comment by Shougo** [comment]
I have implemented local vba path support.

**Comment by Coacher** [comment]
Thanks, but installation from local vimball doesn't work in vim running from terminal. Installation hangs indefinitely showing `[neobundle] -- More --` in the command line. If I run the same installation from gVim, then a separate gVim window opens where I see lots of `extracted ...` and `wrote ...` messages about every file in vimball. I also has to constantly press <Space> to scroll them, otherwise everything hangs indefinitely.

Could you please make vba installation non-interactive?

**Comment by Shougo** [comment]
Unfortunately, I cannot fix it.
Because, it is Vimball feature.  I don't recommend for you to use Vimball.

**Comment by Coacher** [comment]
I see. Thank you for the info.
Sadly some plugins I use are distributed in vimball form only and github vim.org mirror is lagging behind significantly and not maintained actively (https://github.com/vim-scraper/vim-scraper/issues/89).

**Comment by Shougo** [comment]
You can maintain it in github...

**Comment by Coacher** [comment]
Yes, I went down this way in the end, but I was hoping to get good vimball support out of the box with neobundle. I can see now it's impossible due to technical limitations.
