### ISSUE TITLE
Permissions issues when running as different user

### ISSUE THREAD

**Issue by ikogan** [Shougo/neobundle.vim#518]
It looks like the "is_sudo" check doesn't always detect sudo properly. On my setup, I have to administer many different servers as a non-root user, using shared service accounts. Obviously, to do this we sudo as the desired user. That user is then given read access to my login user's `.vimrc` and `.vim` directories. I then run vim with `vim -u /home/myuser/.vimrc` and get the following set of errors:

```
[neobundle] Error generating helptags:
[neobundle] Vim(return):E482: Can't create file /home/myuser/.vim/bundle/.neobundle/doc/pymatcher.txt
Press ENTER or type command to continue
```

It looks like the `is_sudo` function isn't properly detecting sudo in this case. Changing the comparison to simply the following works but I'm concerned it'll break other things:

```vim
return $SUDO_USER != '' && $USER !=# $SUDO_USER
```

**Comment by Shougo** [comment]
I can change the detection.
But it works properly if the user set `always_set_home`?

Current function detects the home directory is not changed.

```vim
  return $SUDO_USER != '' && $USER !=# $SUDO_USER
        \ && $HOME !=# expand('~'.$USER)
        \ && $HOME ==# expand('~'.$SUDO_USER)
```

**Comment by Shougo** [comment]
I think it is better.

Please test it.

```vim
  return $SUDO_USER != '' && $USER !=# $SUDO_USER
      \ && $HOME ==# expand('~'.$USER)
      \ && $HOME !=# expand('~'.$SUDO_USER)
```

**Comment by Shougo** [comment]
I think current routine should work.
Please check your environment.

My sudo result:

```
$SUDO_USER = 'root'
$USER = 'shougo'
$HOME = '/root'
```

$HOME is not `~shougo`, so is_sudo is 0. It should be.

**Comment by ikogan** [comment]
Okay, I'm not sure how this was failing before but it seems to be working now. Sorry about the extra work.
