### ISSUE TITLE
Error E117: Unknown function: neobundle#begin

### ISSUE THREAD

**Issue by Wolficzek** [Shougo/neobundle.vim#519]
Hello! I reinstalled my gvim, installed Neobundle, and getting those errors. I had same problems with Vundle.
```
Error detected while processing function  C:\Vim\_vimrc:
Line    9:
E117: Unknown function: neobundle#begin
Line   13:
E492: Invalid expression::  NeoBundleFetch 'Shougo/neobundle.vim'
Line   19:
E117: Unknown function: neobundle#end
Line   26:
E492: Invalid expression::  NeoBundleCheck
```

Here is my _vimrc fragment:

 ```
set runtimepath+=C:\Vim/bundle/neobundle.vim/

 call neobundle#begin('C:\Vim/bundle')

 NeoBundleFetch 'Shougo/neobundle.vim'

 call neobundle#end()

 filetype plugin indent on
 NeoBundleCheck
```
Using windows 8.1
Gvim 8.0
Installed vim under C:\Vim

**Comment by Shougo** [comment]
I think your runtimepath is invalid.
neobundle is installed in `C:\Vim/bundle/neobundle.vim/`?

**Comment by Wolficzek** [comment]
No, It is installed under C:\Vim\vimfiles\bundle\neobundle.vim 
Is that incorrect?

**Comment by Wolficzek** [comment]
Ohh, it works now, that was the case... Brilliant, thanks a lot!

**Comment by Shougo** [comment]
>No, It is installed under C:\Vim\vimfiles\bundle\neobundle.vim

Oh...
