### ISSUE TITLE
Error when installing bundles in $HOME which has unicode characters on Windows

### ISSUE THREAD

**Issue by yusiwen** [Shougo/neobundle.vim#520]
My windows user home is "C:\Users\斯文". In vim, `echo $HOME` shows it correctly. But `:NeoBundleInstall` reports error as: 
![qq 20161225154714](https://cloud.githubusercontent.com/assets/3704932/21470211/72b16a64-cab9-11e6-9e49-d98a81b21708.png)

It means "E739: Cannot create directory: C:/Users/ [UNICODE]"

I think the unicode characters in the $HOME path causes the problem. How does NeoBundle process them? Can I work it out without changing my $HOME directory's name?

Thanks

**Comment by Shougo** [comment]
You should check the `isdirectory($HOME)`.
I think your encoding configuration is invalid.

**Comment by yusiwen** [comment]
OK. Thanks.
