### ISSUE TITLE
Lazy loading with mapping unclear

### ISSUE THREAD

**Issue by Futurile** [Shougo/neobundle.vim#521]
Hi,

I have tried to read the help and looked at examples in Github, but I cannot get mappings to work.  I think I do not understand how mappings are supposed to work.

I have a plugin that I want to load when the mapping in the plugin is used: the plugin provides a <Plug> mapping for ```<leader>ww``` that calls :VimwikiIndex.

In the new syntax I try this:

```
NeoBundleLazy 'vimwiki/vimwiki', {
                \ 'on_cmd': ['VimwikiIndex'],
                \ 'on_map': ['<Plug>']
                \ }
```
The command :VimwikiIndex is available and works. 

I think this *should* load all mappings that are defined by the plugin. But the mappings are not available, so ```<leader>ww``` does not work. What is my error?

**Comment by Shougo** [comment]
```vim
NeoBundleLazy 'vimwiki/vimwiki', {
                \ 'on_cmd': ['VimwikiIndex'],
                \ 'on_map': ['<leader>ww']
                \ }
```

`<Plug>` is plugin name `vimwiki` prefixed plugin mappings.
But vimwiki defines `Vimwiki` prefixed mappings.
So it does not work.

**Comment by Futurile** [comment]
@Shougo - thank-you. Your suggestion made me *confident* it was something I was doing.

I map ``<space>`` to be my leader, it was mapping fine but it still uses the (``\``) default leader. Defining the mapping with ``<space>`` fixed it for me.

Brilliant - thanks so much!
