### ISSUE TITLE
Checkout branch not tag

### ISSUE THREAD

**Issue by HaleTom** [Shougo/neobundle.vim#530]
When doing:

`NeoBundle 'neoclide/coc.nvim', 'release'`

I get a detached HEAD at `v0.0.71`.

However,  I expect to have branch `release` checked out.

To actually get `release` checked out, I need to do:

`NeoBundle 'neoclide/coc.nvim', 'release', { 'build': { 'others': 'git checkout release' } }`

Am I missing something?

**Comment by Shougo** [comment]
I don't think it is fatal bug and neobundle development is over.

I have tested it in dein.vim.  dein.vim works properly.

So closing.

**Comment by Shougo** [comment]
I have checked the source code.

If you use "release", it means use released tag instead of the branch.
So it is feature of neobundle.vim.

```vim
function! s:type.get_revision_lock_command(bundle) abort "{{{
  if !executable(g:neobundle#types#git#command_path)
    return ''
  endif

  let rev = a:bundle.rev
  if rev ==# 'release'
    " Use latest released tag
    let rev = neobundle#installer#get_release_revision(a:bundle,
          \ g:neobundle#types#git#command_path . ' tag')
  endif
  if rev == ''
    " Fix detach HEAD.
    let rev = 'master'
  endif

  return g:neobundle#types#git#command_path . ' checkout ' . rev
endfunction"}}}
```

**Comment by Shougo** [comment]
It is already documented.  Please read the documentation.

```
		rev			(String)
		Specify a revision number or branch/tag name.
		If it is "release" in "git" type, neobundle will use latest
		released tag.
```

**Comment by HaleTom** [comment]
Thanks for your replies!

I'm now using:

`NeoBundle 'neoclide/coc.nvim', { 'rev': 'release' }`

But still, I have a detached HEAD at `v0.0.71`.

How do I make NeoBundle download and checkout `release` branch?

**Comment by HaleTom** [comment]
I don't understand the difference between `raw type` and `git type`:

> If it is "release" in "git" type, neobundle will use latest released tag.
>		Note: If the type is "raw", rev is hash number.

If it isn't possible to checkout a branch called `release`, then that's fine, I just want to make sure that I'm not missing anything with the format of the value of `rev`.

**Comment by Shougo** [comment]
> How do I make NeoBundle download and checkout release branch?

It is not possible.  It is not supported.

> If you use "release", it means use released tag instead of the branch.

Please read this.

**Comment by Shougo** [comment]
> If it isn't possible to checkout a branch called release, then that's fine

It is not possible.  You are not missing anything.

**Comment by HaleTom** [comment]
Cheers! Thanks for making it crystal clear!
